/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.keys


import org.example.backend.database.tables.Matchdb
import org.example.backend.database.tables.Playerdb
import org.example.backend.database.tables.Tournamentdb
import org.example.backend.database.tables.Usersdb
import org.example.backend.database.tables.records.MatchdbRecord
import org.example.backend.database.tables.records.PlayerdbRecord
import org.example.backend.database.tables.records.TournamentdbRecord
import org.example.backend.database.tables.records.UsersdbRecord
import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val MATCHDB_PKEY: UniqueKey<MatchdbRecord> = Internal.createUniqueKey(Matchdb.MATCHDB, DSL.name("matchdb_pkey"), arrayOf(Matchdb.MATCHDB.ID), true)
val MATCHDB_TOURNAMENT_ID_PLAYER1_ID_PLAYER2_ID_KEY: UniqueKey<MatchdbRecord> = Internal.createUniqueKey(Matchdb.MATCHDB, DSL.name("matchdb_tournament_id_player1_id_player2_id_key"), arrayOf(Matchdb.MATCHDB.TOURNAMENT_ID, Matchdb.MATCHDB.PLAYER1_ID, Matchdb.MATCHDB.PLAYER2_ID), true)
val PLAYERDB_PKEY: UniqueKey<PlayerdbRecord> = Internal.createUniqueKey(Playerdb.PLAYERDB, DSL.name("playerdb_pkey"), arrayOf(Playerdb.PLAYERDB.ID), true)
val TOURNAMENTDB_PKEY: UniqueKey<TournamentdbRecord> = Internal.createUniqueKey(Tournamentdb.TOURNAMENTDB, DSL.name("tournamentdb_pkey"), arrayOf(Tournamentdb.TOURNAMENTDB.ID), true)
val USERSDB_PKEY: UniqueKey<UsersdbRecord> = Internal.createUniqueKey(Usersdb.USERSDB, DSL.name("usersdb_pkey"), arrayOf(Usersdb.USERSDB.ID), true)
val USERSDB_USERNAME_KEY: UniqueKey<UsersdbRecord> = Internal.createUniqueKey(Usersdb.USERSDB, DSL.name("usersdb_username_key"), arrayOf(Usersdb.USERSDB.USERNAME), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val MATCHDB__MATCHDB_PLAYER1_ID_FKEY: ForeignKey<MatchdbRecord, PlayerdbRecord> = Internal.createForeignKey(Matchdb.MATCHDB, DSL.name("matchdb_player1_id_fkey"), arrayOf(Matchdb.MATCHDB.PLAYER1_ID), org.example.backend.database.keys.PLAYERDB_PKEY, arrayOf(Playerdb.PLAYERDB.ID), true)
val MATCHDB__MATCHDB_PLAYER2_ID_FKEY: ForeignKey<MatchdbRecord, PlayerdbRecord> = Internal.createForeignKey(Matchdb.MATCHDB, DSL.name("matchdb_player2_id_fkey"), arrayOf(Matchdb.MATCHDB.PLAYER2_ID), org.example.backend.database.keys.PLAYERDB_PKEY, arrayOf(Playerdb.PLAYERDB.ID), true)
val MATCHDB__MATCHDB_TOURNAMENT_ID_FKEY: ForeignKey<MatchdbRecord, TournamentdbRecord> = Internal.createForeignKey(Matchdb.MATCHDB, DSL.name("matchdb_tournament_id_fkey"), arrayOf(Matchdb.MATCHDB.TOURNAMENT_ID), org.example.backend.database.keys.TOURNAMENTDB_PKEY, arrayOf(Tournamentdb.TOURNAMENTDB.ID), true)
val MATCHDB__MATCHDB_WINNER_ID_FKEY: ForeignKey<MatchdbRecord, PlayerdbRecord> = Internal.createForeignKey(Matchdb.MATCHDB, DSL.name("matchdb_winner_id_fkey"), arrayOf(Matchdb.MATCHDB.WINNER_ID), org.example.backend.database.keys.PLAYERDB_PKEY, arrayOf(Playerdb.PLAYERDB.ID), true)
val PLAYERDB__PLAYERDB_TOURNAMENT_ID_FKEY: ForeignKey<PlayerdbRecord, TournamentdbRecord> = Internal.createForeignKey(Playerdb.PLAYERDB, DSL.name("playerdb_tournament_id_fkey"), arrayOf(Playerdb.PLAYERDB.TOURNAMENT_ID), org.example.backend.database.keys.TOURNAMENTDB_PKEY, arrayOf(Tournamentdb.TOURNAMENTDB.ID), true)
val PLAYERDB__PLAYERDB_USER_ID_FKEY: ForeignKey<PlayerdbRecord, PlayerdbRecord> = Internal.createForeignKey(Playerdb.PLAYERDB, DSL.name("playerdb_user_id_fkey"), arrayOf(Playerdb.PLAYERDB.USER_ID), org.example.backend.database.keys.PLAYERDB_PKEY, arrayOf(Playerdb.PLAYERDB.ID), true)
