/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.enums


import org.example.backend.database.Public
import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class BracketType(@get:JvmName("literal") public val literal: String) : EnumType {
    winner("winner"),
    loser("loser"),
    grand_final("grand_final"),
    group("group");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "bracket_type"
    override fun getLiteral(): String = literal
}
