/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.enums


import org.example.backend.database.Public
import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class MatchStatus(@get:JvmName("literal") public val literal: String) : EnumType {
    pending("pending"),
    ongoing("ongoing"),
    finished("finished"),
    disputed("disputed"),
    forfeited("forfeited");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "match_status"
    override fun getLiteral(): String = literal
}
