/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.enums


import org.example.backend.database.Public
import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class NotificationEvent(@get:JvmName("literal") public val literal: String) : EnumType {
    match_starting("match_starting"),
    registration_validated("registration_validated"),
    score_disputed("score_disputed"),
    tournament_starting("tournament_starting");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "notification_event"
    override fun getLiteral(): String = literal
}
