/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.enums


import org.example.backend.database.Public
import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class PhaseType(@get:JvmName("literal") public val literal: String) : EnumType {
    single_elim("single_elim"),
    double_elim("double_elim"),
    round_robin("round_robin"),
    swiss("swiss");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "phase_type"
    override fun getLiteral(): String = literal
}
