/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.enums


import org.example.backend.database.Public
import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class RegistrationStatus(@get:JvmName("literal") public val literal: String) : EnumType {
    pending("pending"),
    confirmed("confirmed"),
    waitlist("waitlist"),
    checked_in("checked_in"),
    withdrawn("withdrawn"),
    disqualified("disqualified");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "registration_status"
    override fun getLiteral(): String = literal
}
