spring:
  application:
    name: backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mypassword
  jooq:
    sql-dialect: POSTGRES



