/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables


import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.example.backend.database.Public
import org.example.backend.database.indexes.IDX_ANNOUNCEMENTS_TOURNAMENT_DATE
import org.example.backend.database.keys.ANNOUNCEMENTS_PKEY
import org.example.backend.database.keys.ANNOUNCEMENTS__ANNOUNCEMENTS_TOURNAMENT_ID_FKEY
import org.example.backend.database.tables.Tournaments.TournamentsPath
import org.example.backend.database.tables.records.AnnouncementsRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Announcements(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, AnnouncementsRecord>?,
    parentPath: InverseForeignKey<out Record, AnnouncementsRecord>?,
    aliased: Table<AnnouncementsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<AnnouncementsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.announcements</code>
         */
        val ANNOUNCEMENTS: Announcements = Announcements()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AnnouncementsRecord> = AnnouncementsRecord::class.java

    /**
     * The column <code>public.announcements.id</code>.
     */
    val ID: TableField<AnnouncementsRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.announcements.tournament_id</code>.
     */
    val TOURNAMENT_ID: TableField<AnnouncementsRecord, UUID?> = createField(DSL.name("tournament_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.announcements.kind</code>.
     */
    val KIND: TableField<AnnouncementsRecord, String?> = createField(DSL.name("kind"), SQLDataType.VARCHAR.nullable(false), this, "")

    /**
     * The column <code>public.announcements.message</code>.
     */
    val MESSAGE: TableField<AnnouncementsRecord, String?> = createField(DSL.name("message"), SQLDataType.VARCHAR.nullable(false), this, "")

    /**
     * The column <code>public.announcements.created_at</code>.
     */
    val CREATED_AT: TableField<AnnouncementsRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<AnnouncementsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<AnnouncementsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<AnnouncementsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.announcements</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.announcements</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.announcements</code> table reference
     */
    constructor(): this(DSL.name("announcements"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, AnnouncementsRecord>?, parentPath: InverseForeignKey<out Record, AnnouncementsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, ANNOUNCEMENTS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class AnnouncementsPath : Announcements, Path<AnnouncementsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, AnnouncementsRecord>?, parentPath: InverseForeignKey<out Record, AnnouncementsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<AnnouncementsRecord>): super(alias, aliased)
        override fun `as`(alias: String): AnnouncementsPath = AnnouncementsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): AnnouncementsPath = AnnouncementsPath(alias, this)
        override fun `as`(alias: Table<*>): AnnouncementsPath = AnnouncementsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_ANNOUNCEMENTS_TOURNAMENT_DATE)
    override fun getPrimaryKey(): UniqueKey<AnnouncementsRecord> = ANNOUNCEMENTS_PKEY
    override fun getReferences(): List<ForeignKey<AnnouncementsRecord, *>> = listOf(ANNOUNCEMENTS__ANNOUNCEMENTS_TOURNAMENT_ID_FKEY)

    private lateinit var _tournaments: TournamentsPath

    /**
     * Get the implicit join path to the <code>public.tournaments</code> table.
     */
    fun tournaments(): TournamentsPath {
        if (!this::_tournaments.isInitialized)
            _tournaments = TournamentsPath(this, ANNOUNCEMENTS__ANNOUNCEMENTS_TOURNAMENT_ID_FKEY, null)

        return _tournaments;
    }

    val tournaments: TournamentsPath
        get(): TournamentsPath = tournaments()
    override fun `as`(alias: String): Announcements = Announcements(DSL.name(alias), this)
    override fun `as`(alias: Name): Announcements = Announcements(alias, this)
    override fun `as`(alias: Table<*>): Announcements = Announcements(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Announcements = Announcements(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Announcements = Announcements(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Announcements = Announcements(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Announcements = Announcements(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Announcements = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Announcements = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Announcements = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Announcements = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Announcements = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Announcements = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Announcements = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Announcements = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Announcements = where(DSL.notExists(select))
}
