/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables


import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.example.backend.database.Public
import org.example.backend.database.enums.DisputeStatus
import org.example.backend.database.keys.DISPUTES_PKEY
import org.example.backend.database.keys.DISPUTES__DISPUTES_MATCH_ID_FKEY
import org.example.backend.database.keys.DISPUTES__DISPUTES_OPENED_BY_FKEY
import org.example.backend.database.keys.DISPUTES__DISPUTES_RESOLVED_BY_FKEY
import org.example.backend.database.tables.Matches.MatchesPath
import org.example.backend.database.tables.Users.UsersPath
import org.example.backend.database.tables.records.DisputesRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Disputes(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, DisputesRecord>?,
    parentPath: InverseForeignKey<out Record, DisputesRecord>?,
    aliased: Table<DisputesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<DisputesRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.disputes</code>
         */
        val DISPUTES: Disputes = Disputes()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<DisputesRecord> = DisputesRecord::class.java

    /**
     * The column <code>public.disputes.id</code>.
     */
    val ID: TableField<DisputesRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.disputes.match_id</code>.
     */
    val MATCH_ID: TableField<DisputesRecord, UUID?> = createField(DSL.name("match_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.disputes.opened_by</code>.
     */
    val OPENED_BY: TableField<DisputesRecord, UUID?> = createField(DSL.name("opened_by"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.disputes.evidence_url</code>.
     */
    val EVIDENCE_URL: TableField<DisputesRecord, String?> = createField(DSL.name("evidence_url"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>public.disputes.status</code>.
     */
    val STATUS: TableField<DisputesRecord, DisputeStatus?> = createField(DSL.name("status"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field(DSL.raw("'open'::dispute_status"), SQLDataType.VARCHAR)).asEnumDataType(DisputeStatus::class.java), this, "")

    /**
     * The column <code>public.disputes.resolved_by</code>.
     */
    val RESOLVED_BY: TableField<DisputesRecord, UUID?> = createField(DSL.name("resolved_by"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.disputes.resolution</code>.
     */
    val RESOLUTION: TableField<DisputesRecord, String?> = createField(DSL.name("resolution"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.disputes.created_at</code>.
     */
    val CREATED_AT: TableField<DisputesRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<DisputesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<DisputesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<DisputesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.disputes</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.disputes</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.disputes</code> table reference
     */
    constructor(): this(DSL.name("disputes"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, DisputesRecord>?, parentPath: InverseForeignKey<out Record, DisputesRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, DISPUTES, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class DisputesPath : Disputes, Path<DisputesRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, DisputesRecord>?, parentPath: InverseForeignKey<out Record, DisputesRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<DisputesRecord>): super(alias, aliased)
        override fun `as`(alias: String): DisputesPath = DisputesPath(DSL.name(alias), this)
        override fun `as`(alias: Name): DisputesPath = DisputesPath(alias, this)
        override fun `as`(alias: Table<*>): DisputesPath = DisputesPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<DisputesRecord> = DISPUTES_PKEY
    override fun getReferences(): List<ForeignKey<DisputesRecord, *>> = listOf(DISPUTES__DISPUTES_MATCH_ID_FKEY, DISPUTES__DISPUTES_OPENED_BY_FKEY, DISPUTES__DISPUTES_RESOLVED_BY_FKEY)

    private lateinit var _matches: MatchesPath

    /**
     * Get the implicit join path to the <code>public.matches</code> table.
     */
    fun matches(): MatchesPath {
        if (!this::_matches.isInitialized)
            _matches = MatchesPath(this, DISPUTES__DISPUTES_MATCH_ID_FKEY, null)

        return _matches;
    }

    val matches: MatchesPath
        get(): MatchesPath = matches()

    private lateinit var _disputesOpenedByFkey: UsersPath

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>disputes_opened_by_fkey</code> key.
     */
    fun disputesOpenedByFkey(): UsersPath {
        if (!this::_disputesOpenedByFkey.isInitialized)
            _disputesOpenedByFkey = UsersPath(this, DISPUTES__DISPUTES_OPENED_BY_FKEY, null)

        return _disputesOpenedByFkey;
    }

    val disputesOpenedByFkey: UsersPath
        get(): UsersPath = disputesOpenedByFkey()

    private lateinit var _disputesResolvedByFkey: UsersPath

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>disputes_resolved_by_fkey</code> key.
     */
    fun disputesResolvedByFkey(): UsersPath {
        if (!this::_disputesResolvedByFkey.isInitialized)
            _disputesResolvedByFkey = UsersPath(this, DISPUTES__DISPUTES_RESOLVED_BY_FKEY, null)

        return _disputesResolvedByFkey;
    }

    val disputesResolvedByFkey: UsersPath
        get(): UsersPath = disputesResolvedByFkey()
    override fun `as`(alias: String): Disputes = Disputes(DSL.name(alias), this)
    override fun `as`(alias: Name): Disputes = Disputes(alias, this)
    override fun `as`(alias: Table<*>): Disputes = Disputes(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Disputes = Disputes(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Disputes = Disputes(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Disputes = Disputes(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Disputes = Disputes(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Disputes = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Disputes = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Disputes = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Disputes = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Disputes = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Disputes = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Disputes = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Disputes = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Disputes = where(DSL.notExists(select))
}
