/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables


import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.example.backend.database.Public
import org.example.backend.database.keys.GAME_ACCOUNTS_PKEY
import org.example.backend.database.keys.GAME_ACCOUNTS__GAME_ACCOUNTS_USER_ID_FKEY
import org.example.backend.database.tables.Users.UsersPath
import org.example.backend.database.tables.records.GameAccountsRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class GameAccounts(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, GameAccountsRecord>?,
    parentPath: InverseForeignKey<out Record, GameAccountsRecord>?,
    aliased: Table<GameAccountsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<GameAccountsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.game_accounts</code>
         */
        val GAME_ACCOUNTS: GameAccounts = GameAccounts()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<GameAccountsRecord> = GameAccountsRecord::class.java

    /**
     * The column <code>public.game_accounts.id</code>.
     */
    val ID: TableField<GameAccountsRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.game_accounts.user_id</code>.
     */
    val USER_ID: TableField<GameAccountsRecord, UUID?> = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.game_accounts.game</code>.
     */
    val GAME: TableField<GameAccountsRecord, String?> = createField(DSL.name("game"), SQLDataType.VARCHAR.nullable(false), this, "")

    /**
     * The column <code>public.game_accounts.identifier</code>.
     */
    val IDENTIFIER: TableField<GameAccountsRecord, String?> = createField(DSL.name("identifier"), SQLDataType.VARCHAR.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<GameAccountsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<GameAccountsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<GameAccountsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.game_accounts</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.game_accounts</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.game_accounts</code> table reference
     */
    constructor(): this(DSL.name("game_accounts"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, GameAccountsRecord>?, parentPath: InverseForeignKey<out Record, GameAccountsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, GAME_ACCOUNTS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class GameAccountsPath : GameAccounts, Path<GameAccountsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, GameAccountsRecord>?, parentPath: InverseForeignKey<out Record, GameAccountsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<GameAccountsRecord>): super(alias, aliased)
        override fun `as`(alias: String): GameAccountsPath = GameAccountsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): GameAccountsPath = GameAccountsPath(alias, this)
        override fun `as`(alias: Table<*>): GameAccountsPath = GameAccountsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<GameAccountsRecord> = GAME_ACCOUNTS_PKEY
    override fun getReferences(): List<ForeignKey<GameAccountsRecord, *>> = listOf(GAME_ACCOUNTS__GAME_ACCOUNTS_USER_ID_FKEY)

    private lateinit var _users: UsersPath

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    fun users(): UsersPath {
        if (!this::_users.isInitialized)
            _users = UsersPath(this, GAME_ACCOUNTS__GAME_ACCOUNTS_USER_ID_FKEY, null)

        return _users;
    }

    val users: UsersPath
        get(): UsersPath = users()
    override fun `as`(alias: String): GameAccounts = GameAccounts(DSL.name(alias), this)
    override fun `as`(alias: Name): GameAccounts = GameAccounts(alias, this)
    override fun `as`(alias: Table<*>): GameAccounts = GameAccounts(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): GameAccounts = GameAccounts(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): GameAccounts = GameAccounts(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): GameAccounts = GameAccounts(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): GameAccounts = GameAccounts(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): GameAccounts = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): GameAccounts = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): GameAccounts = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): GameAccounts = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): GameAccounts = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): GameAccounts = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): GameAccounts = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): GameAccounts = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): GameAccounts = where(DSL.notExists(select))
}
