/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables


import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.example.backend.database.Public
import org.example.backend.database.keys.MATCH_GAMES_PKEY
import org.example.backend.database.keys.MATCH_GAMES__MATCH_GAMES_MATCH_ID_FKEY
import org.example.backend.database.tables.Matches.MatchesPath
import org.example.backend.database.tables.records.MatchGamesRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class MatchGames(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, MatchGamesRecord>?,
    parentPath: InverseForeignKey<out Record, MatchGamesRecord>?,
    aliased: Table<MatchGamesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<MatchGamesRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.match_games</code>
         */
        val MATCH_GAMES: MatchGames = MatchGames()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<MatchGamesRecord> = MatchGamesRecord::class.java

    /**
     * The column <code>public.match_games.id</code>.
     */
    val ID: TableField<MatchGamesRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.match_games.match_id</code>.
     */
    val MATCH_ID: TableField<MatchGamesRecord, UUID?> = createField(DSL.name("match_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.match_games.game_number</code>.
     */
    val GAME_NUMBER: TableField<MatchGamesRecord, Int?> = createField(DSL.name("game_number"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.match_games.score1</code>.
     */
    val SCORE1: TableField<MatchGamesRecord, Int?> = createField(DSL.name("score1"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.match_games.score2</code>.
     */
    val SCORE2: TableField<MatchGamesRecord, Int?> = createField(DSL.name("score2"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<MatchGamesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<MatchGamesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<MatchGamesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.match_games</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.match_games</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.match_games</code> table reference
     */
    constructor(): this(DSL.name("match_games"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, MatchGamesRecord>?, parentPath: InverseForeignKey<out Record, MatchGamesRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, MATCH_GAMES, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class MatchGamesPath : MatchGames, Path<MatchGamesRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, MatchGamesRecord>?, parentPath: InverseForeignKey<out Record, MatchGamesRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<MatchGamesRecord>): super(alias, aliased)
        override fun `as`(alias: String): MatchGamesPath = MatchGamesPath(DSL.name(alias), this)
        override fun `as`(alias: Name): MatchGamesPath = MatchGamesPath(alias, this)
        override fun `as`(alias: Table<*>): MatchGamesPath = MatchGamesPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<MatchGamesRecord> = MATCH_GAMES_PKEY
    override fun getReferences(): List<ForeignKey<MatchGamesRecord, *>> = listOf(MATCH_GAMES__MATCH_GAMES_MATCH_ID_FKEY)

    private lateinit var _matches: MatchesPath

    /**
     * Get the implicit join path to the <code>public.matches</code> table.
     */
    fun matches(): MatchesPath {
        if (!this::_matches.isInitialized)
            _matches = MatchesPath(this, MATCH_GAMES__MATCH_GAMES_MATCH_ID_FKEY, null)

        return _matches;
    }

    val matches: MatchesPath
        get(): MatchesPath = matches()
    override fun `as`(alias: String): MatchGames = MatchGames(DSL.name(alias), this)
    override fun `as`(alias: Name): MatchGames = MatchGames(alias, this)
    override fun `as`(alias: Table<*>): MatchGames = MatchGames(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): MatchGames = MatchGames(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): MatchGames = MatchGames(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): MatchGames = MatchGames(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): MatchGames = MatchGames(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): MatchGames = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): MatchGames = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): MatchGames = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): MatchGames = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): MatchGames = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): MatchGames = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): MatchGames = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): MatchGames = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): MatchGames = where(DSL.notExists(select))
}
