/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables


import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.example.backend.database.Public
import org.example.backend.database.keys.MATCHDB_PKEY
import org.example.backend.database.keys.MATCHDB_TOURNAMENT_ID_PLAYER1_ID_PLAYER2_ID_KEY
import org.example.backend.database.keys.MATCHDB__MATCHDB_PLAYER1_ID_FKEY
import org.example.backend.database.keys.MATCHDB__MATCHDB_PLAYER2_ID_FKEY
import org.example.backend.database.keys.MATCHDB__MATCHDB_TOURNAMENT_ID_FKEY
import org.example.backend.database.keys.MATCHDB__MATCHDB_WINNER_ID_FKEY
import org.example.backend.database.tables.Playerdb.PlayerdbPath
import org.example.backend.database.tables.Tournamentdb.TournamentdbPath
import org.example.backend.database.tables.records.MatchdbRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Matchdb(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, MatchdbRecord>?,
    parentPath: InverseForeignKey<out Record, MatchdbRecord>?,
    aliased: Table<MatchdbRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<MatchdbRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.matchdb</code>
         */
        val MATCHDB: Matchdb = Matchdb()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<MatchdbRecord> = MatchdbRecord::class.java

    /**
     * The column <code>public.matchdb.id</code>.
     */
    val ID: TableField<MatchdbRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.matchdb.tournament_id</code>.
     */
    val TOURNAMENT_ID: TableField<MatchdbRecord, Long?> = createField(DSL.name("tournament_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.matchdb.player1_id</code>.
     */
    val PLAYER1_ID: TableField<MatchdbRecord, Long?> = createField(DSL.name("player1_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.matchdb.player2_id</code>.
     */
    val PLAYER2_ID: TableField<MatchdbRecord, Long?> = createField(DSL.name("player2_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.matchdb.winner_id</code>.
     */
    val WINNER_ID: TableField<MatchdbRecord, Long?> = createField(DSL.name("winner_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>public.matchdb.score_player1</code>.
     */
    val SCORE_PLAYER1: TableField<MatchdbRecord, Int?> = createField(DSL.name("score_player1"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>public.matchdb.score_player2</code>.
     */
    val SCORE_PLAYER2: TableField<MatchdbRecord, Int?> = createField(DSL.name("score_player2"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>public.matchdb.played_at</code>.
     */
    val PLAYED_AT: TableField<MatchdbRecord, LocalDateTime?> = createField(DSL.name("played_at"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column <code>public.matchdb.created_at</code>.
     */
    val CREATED_AT: TableField<MatchdbRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<MatchdbRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<MatchdbRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<MatchdbRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.matchdb</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.matchdb</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.matchdb</code> table reference
     */
    constructor(): this(DSL.name("matchdb"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, MatchdbRecord>?, parentPath: InverseForeignKey<out Record, MatchdbRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, MATCHDB, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class MatchdbPath : Matchdb, Path<MatchdbRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, MatchdbRecord>?, parentPath: InverseForeignKey<out Record, MatchdbRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<MatchdbRecord>): super(alias, aliased)
        override fun `as`(alias: String): MatchdbPath = MatchdbPath(DSL.name(alias), this)
        override fun `as`(alias: Name): MatchdbPath = MatchdbPath(alias, this)
        override fun `as`(alias: Table<*>): MatchdbPath = MatchdbPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<MatchdbRecord> = MATCHDB_PKEY
    override fun getUniqueKeys(): List<UniqueKey<MatchdbRecord>> = listOf(MATCHDB_TOURNAMENT_ID_PLAYER1_ID_PLAYER2_ID_KEY)
    override fun getReferences(): List<ForeignKey<MatchdbRecord, *>> = listOf(MATCHDB__MATCHDB_PLAYER1_ID_FKEY, MATCHDB__MATCHDB_PLAYER2_ID_FKEY, MATCHDB__MATCHDB_TOURNAMENT_ID_FKEY, MATCHDB__MATCHDB_WINNER_ID_FKEY)

    private lateinit var _matchdbPlayer1IdFkey: PlayerdbPath

    /**
     * Get the implicit join path to the <code>public.playerdb</code> table, via
     * the <code>matchdb_player1_id_fkey</code> key.
     */
    fun matchdbPlayer1IdFkey(): PlayerdbPath {
        if (!this::_matchdbPlayer1IdFkey.isInitialized)
            _matchdbPlayer1IdFkey = PlayerdbPath(this, MATCHDB__MATCHDB_PLAYER1_ID_FKEY, null)

        return _matchdbPlayer1IdFkey;
    }

    val matchdbPlayer1IdFkey: PlayerdbPath
        get(): PlayerdbPath = matchdbPlayer1IdFkey()

    private lateinit var _matchdbPlayer2IdFkey: PlayerdbPath

    /**
     * Get the implicit join path to the <code>public.playerdb</code> table, via
     * the <code>matchdb_player2_id_fkey</code> key.
     */
    fun matchdbPlayer2IdFkey(): PlayerdbPath {
        if (!this::_matchdbPlayer2IdFkey.isInitialized)
            _matchdbPlayer2IdFkey = PlayerdbPath(this, MATCHDB__MATCHDB_PLAYER2_ID_FKEY, null)

        return _matchdbPlayer2IdFkey;
    }

    val matchdbPlayer2IdFkey: PlayerdbPath
        get(): PlayerdbPath = matchdbPlayer2IdFkey()

    private lateinit var _tournamentdb: TournamentdbPath

    /**
     * Get the implicit join path to the <code>public.tournamentdb</code> table.
     */
    fun tournamentdb(): TournamentdbPath {
        if (!this::_tournamentdb.isInitialized)
            _tournamentdb = TournamentdbPath(this, MATCHDB__MATCHDB_TOURNAMENT_ID_FKEY, null)

        return _tournamentdb;
    }

    val tournamentdb: TournamentdbPath
        get(): TournamentdbPath = tournamentdb()

    private lateinit var _matchdbWinnerIdFkey: PlayerdbPath

    /**
     * Get the implicit join path to the <code>public.playerdb</code> table, via
     * the <code>matchdb_winner_id_fkey</code> key.
     */
    fun matchdbWinnerIdFkey(): PlayerdbPath {
        if (!this::_matchdbWinnerIdFkey.isInitialized)
            _matchdbWinnerIdFkey = PlayerdbPath(this, MATCHDB__MATCHDB_WINNER_ID_FKEY, null)

        return _matchdbWinnerIdFkey;
    }

    val matchdbWinnerIdFkey: PlayerdbPath
        get(): PlayerdbPath = matchdbWinnerIdFkey()
    override fun `as`(alias: String): Matchdb = Matchdb(DSL.name(alias), this)
    override fun `as`(alias: Name): Matchdb = Matchdb(alias, this)
    override fun `as`(alias: Table<*>): Matchdb = Matchdb(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Matchdb = Matchdb(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Matchdb = Matchdb(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Matchdb = Matchdb(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Matchdb = Matchdb(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Matchdb = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Matchdb = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Matchdb = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Matchdb = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Matchdb = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Matchdb = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Matchdb = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Matchdb = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Matchdb = where(DSL.notExists(select))
}
