/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables


import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.example.backend.database.Public
import org.example.backend.database.enums.BracketType
import org.example.backend.database.enums.MatchStatus
import org.example.backend.database.indexes.IDX_MATCHES_PHASE
import org.example.backend.database.keys.DISPUTES__DISPUTES_MATCH_ID_FKEY
import org.example.backend.database.keys.MATCHES_PKEY
import org.example.backend.database.keys.MATCHES__MATCHES_NEXT_MATCH_ID_FKEY
import org.example.backend.database.keys.MATCHES__MATCHES_NEXT_MATCH_LOSER_ID_FKEY
import org.example.backend.database.keys.MATCHES__MATCHES_PARTICIPANT1_ID_FKEY
import org.example.backend.database.keys.MATCHES__MATCHES_PARTICIPANT2_ID_FKEY
import org.example.backend.database.keys.MATCHES__MATCHES_PHASE_ID_FKEY
import org.example.backend.database.keys.MATCHES__MATCHES_WINNER_ID_FKEY
import org.example.backend.database.keys.MATCH_GAMES__MATCH_GAMES_MATCH_ID_FKEY
import org.example.backend.database.keys.SCORE_REPORTS__SCORE_REPORTS_MATCH_ID_FKEY
import org.example.backend.database.tables.Disputes.DisputesPath
import org.example.backend.database.tables.MatchGames.MatchGamesPath
import org.example.backend.database.tables.Matches.MatchesPath
import org.example.backend.database.tables.Phases.PhasesPath
import org.example.backend.database.tables.Registrations.RegistrationsPath
import org.example.backend.database.tables.ScoreReports.ScoreReportsPath
import org.example.backend.database.tables.records.MatchesRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Matches(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, MatchesRecord>?,
    parentPath: InverseForeignKey<out Record, MatchesRecord>?,
    aliased: Table<MatchesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<MatchesRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.matches</code>
         */
        val MATCHES: Matches = Matches()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<MatchesRecord> = MatchesRecord::class.java

    /**
     * The column <code>public.matches.id</code>.
     */
    val ID: TableField<MatchesRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.matches.phase_id</code>.
     */
    val PHASE_ID: TableField<MatchesRecord, UUID?> = createField(DSL.name("phase_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.matches.round</code>.
     */
    val ROUND: TableField<MatchesRecord, Int?> = createField(DSL.name("round"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.matches.position</code>.
     */
    val POSITION: TableField<MatchesRecord, Int?> = createField(DSL.name("position"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.matches.bracket</code>.
     */
    val BRACKET: TableField<MatchesRecord, BracketType?> = createField(DSL.name("bracket"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field(DSL.raw("'winner'::bracket_type"), SQLDataType.VARCHAR)).asEnumDataType(BracketType::class.java), this, "")

    /**
     * The column <code>public.matches.best_of</code>.
     */
    val BEST_OF: TableField<MatchesRecord, Int?> = createField(DSL.name("best_of"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>public.matches.participant1_id</code>.
     */
    val PARTICIPANT1_ID: TableField<MatchesRecord, UUID?> = createField(DSL.name("participant1_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.matches.participant2_id</code>.
     */
    val PARTICIPANT2_ID: TableField<MatchesRecord, UUID?> = createField(DSL.name("participant2_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.matches.winner_id</code>.
     */
    val WINNER_ID: TableField<MatchesRecord, UUID?> = createField(DSL.name("winner_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.matches.status</code>.
     */
    val STATUS: TableField<MatchesRecord, MatchStatus?> = createField(DSL.name("status"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field(DSL.raw("'pending'::match_status"), SQLDataType.VARCHAR)).asEnumDataType(MatchStatus::class.java), this, "")

    /**
     * The column <code>public.matches.next_match_id</code>.
     */
    val NEXT_MATCH_ID: TableField<MatchesRecord, UUID?> = createField(DSL.name("next_match_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.matches.next_match_loser_id</code>.
     */
    val NEXT_MATCH_LOSER_ID: TableField<MatchesRecord, UUID?> = createField(DSL.name("next_match_loser_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.matches.scheduled_at</code>.
     */
    val SCHEDULED_AT: TableField<MatchesRecord, OffsetDateTime?> = createField(DSL.name("scheduled_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.matches.station</code>.
     */
    val STATION: TableField<MatchesRecord, String?> = createField(DSL.name("station"), SQLDataType.VARCHAR, this, "")

    private constructor(alias: Name, aliased: Table<MatchesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<MatchesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<MatchesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.matches</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.matches</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.matches</code> table reference
     */
    constructor(): this(DSL.name("matches"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, MatchesRecord>?, parentPath: InverseForeignKey<out Record, MatchesRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, MATCHES, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class MatchesPath : Matches, Path<MatchesRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, MatchesRecord>?, parentPath: InverseForeignKey<out Record, MatchesRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<MatchesRecord>): super(alias, aliased)
        override fun `as`(alias: String): MatchesPath = MatchesPath(DSL.name(alias), this)
        override fun `as`(alias: Name): MatchesPath = MatchesPath(alias, this)
        override fun `as`(alias: Table<*>): MatchesPath = MatchesPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_MATCHES_PHASE)
    override fun getPrimaryKey(): UniqueKey<MatchesRecord> = MATCHES_PKEY
    override fun getReferences(): List<ForeignKey<MatchesRecord, *>> = listOf(MATCHES__MATCHES_NEXT_MATCH_ID_FKEY, MATCHES__MATCHES_NEXT_MATCH_LOSER_ID_FKEY, MATCHES__MATCHES_PARTICIPANT1_ID_FKEY, MATCHES__MATCHES_PARTICIPANT2_ID_FKEY, MATCHES__MATCHES_PHASE_ID_FKEY, MATCHES__MATCHES_WINNER_ID_FKEY)

    private lateinit var _matchesNextMatchIdFkey: MatchesPath

    /**
     * Get the implicit join path to the <code>public.matches</code> table, via
     * the <code>matches_next_match_id_fkey</code> key.
     */
    fun matchesNextMatchIdFkey(): MatchesPath {
        if (!this::_matchesNextMatchIdFkey.isInitialized)
            _matchesNextMatchIdFkey = MatchesPath(this, MATCHES__MATCHES_NEXT_MATCH_ID_FKEY, null)

        return _matchesNextMatchIdFkey;
    }

    val matchesNextMatchIdFkey: MatchesPath
        get(): MatchesPath = matchesNextMatchIdFkey()

    private lateinit var _matchesNextMatchLoserIdFkey: MatchesPath

    /**
     * Get the implicit join path to the <code>public.matches</code> table, via
     * the <code>matches_next_match_loser_id_fkey</code> key.
     */
    fun matchesNextMatchLoserIdFkey(): MatchesPath {
        if (!this::_matchesNextMatchLoserIdFkey.isInitialized)
            _matchesNextMatchLoserIdFkey = MatchesPath(this, MATCHES__MATCHES_NEXT_MATCH_LOSER_ID_FKEY, null)

        return _matchesNextMatchLoserIdFkey;
    }

    val matchesNextMatchLoserIdFkey: MatchesPath
        get(): MatchesPath = matchesNextMatchLoserIdFkey()

    private lateinit var _matchesParticipant1IdFkey: RegistrationsPath

    /**
     * Get the implicit join path to the <code>public.registrations</code>
     * table, via the <code>matches_participant1_id_fkey</code> key.
     */
    fun matchesParticipant1IdFkey(): RegistrationsPath {
        if (!this::_matchesParticipant1IdFkey.isInitialized)
            _matchesParticipant1IdFkey = RegistrationsPath(this, MATCHES__MATCHES_PARTICIPANT1_ID_FKEY, null)

        return _matchesParticipant1IdFkey;
    }

    val matchesParticipant1IdFkey: RegistrationsPath
        get(): RegistrationsPath = matchesParticipant1IdFkey()

    private lateinit var _matchesParticipant2IdFkey: RegistrationsPath

    /**
     * Get the implicit join path to the <code>public.registrations</code>
     * table, via the <code>matches_participant2_id_fkey</code> key.
     */
    fun matchesParticipant2IdFkey(): RegistrationsPath {
        if (!this::_matchesParticipant2IdFkey.isInitialized)
            _matchesParticipant2IdFkey = RegistrationsPath(this, MATCHES__MATCHES_PARTICIPANT2_ID_FKEY, null)

        return _matchesParticipant2IdFkey;
    }

    val matchesParticipant2IdFkey: RegistrationsPath
        get(): RegistrationsPath = matchesParticipant2IdFkey()

    private lateinit var _phases: PhasesPath

    /**
     * Get the implicit join path to the <code>public.phases</code> table.
     */
    fun phases(): PhasesPath {
        if (!this::_phases.isInitialized)
            _phases = PhasesPath(this, MATCHES__MATCHES_PHASE_ID_FKEY, null)

        return _phases;
    }

    val phases: PhasesPath
        get(): PhasesPath = phases()

    private lateinit var _matchesWinnerIdFkey: RegistrationsPath

    /**
     * Get the implicit join path to the <code>public.registrations</code>
     * table, via the <code>matches_winner_id_fkey</code> key.
     */
    fun matchesWinnerIdFkey(): RegistrationsPath {
        if (!this::_matchesWinnerIdFkey.isInitialized)
            _matchesWinnerIdFkey = RegistrationsPath(this, MATCHES__MATCHES_WINNER_ID_FKEY, null)

        return _matchesWinnerIdFkey;
    }

    val matchesWinnerIdFkey: RegistrationsPath
        get(): RegistrationsPath = matchesWinnerIdFkey()

    private lateinit var _disputes: DisputesPath

    /**
     * Get the implicit to-many join path to the <code>public.disputes</code>
     * table
     */
    fun disputes(): DisputesPath {
        if (!this::_disputes.isInitialized)
            _disputes = DisputesPath(this, null, DISPUTES__DISPUTES_MATCH_ID_FKEY.inverseKey)

        return _disputes;
    }

    val disputes: DisputesPath
        get(): DisputesPath = disputes()

    private lateinit var _matchGames: MatchGamesPath

    /**
     * Get the implicit to-many join path to the <code>public.match_games</code>
     * table
     */
    fun matchGames(): MatchGamesPath {
        if (!this::_matchGames.isInitialized)
            _matchGames = MatchGamesPath(this, null, MATCH_GAMES__MATCH_GAMES_MATCH_ID_FKEY.inverseKey)

        return _matchGames;
    }

    val matchGames: MatchGamesPath
        get(): MatchGamesPath = matchGames()

    private lateinit var _scoreReports: ScoreReportsPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.score_reports</code> table
     */
    fun scoreReports(): ScoreReportsPath {
        if (!this::_scoreReports.isInitialized)
            _scoreReports = ScoreReportsPath(this, null, SCORE_REPORTS__SCORE_REPORTS_MATCH_ID_FKEY.inverseKey)

        return _scoreReports;
    }

    val scoreReports: ScoreReportsPath
        get(): ScoreReportsPath = scoreReports()
    override fun `as`(alias: String): Matches = Matches(DSL.name(alias), this)
    override fun `as`(alias: Name): Matches = Matches(alias, this)
    override fun `as`(alias: Table<*>): Matches = Matches(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Matches = Matches(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Matches = Matches(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Matches = Matches(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Matches = Matches(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Matches = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Matches = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Matches = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Matches = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Matches = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Matches = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Matches = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Matches = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Matches = where(DSL.notExists(select))
}
