/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables


import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.example.backend.database.Public
import org.example.backend.database.enums.NotificationChannel
import org.example.backend.database.enums.NotificationEvent
import org.example.backend.database.keys.NOTIFICATION_SETTINGS_PKEY
import org.example.backend.database.keys.NOTIFICATION_SETTINGS__NOTIFICATION_SETTINGS_USER_ID_FKEY
import org.example.backend.database.tables.Users.UsersPath
import org.example.backend.database.tables.records.NotificationSettingsRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class NotificationSettings(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, NotificationSettingsRecord>?,
    parentPath: InverseForeignKey<out Record, NotificationSettingsRecord>?,
    aliased: Table<NotificationSettingsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<NotificationSettingsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.notification_settings</code>
         */
        val NOTIFICATION_SETTINGS: NotificationSettings = NotificationSettings()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<NotificationSettingsRecord> = NotificationSettingsRecord::class.java

    /**
     * The column <code>public.notification_settings.id</code>.
     */
    val ID: TableField<NotificationSettingsRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.notification_settings.user_id</code>.
     */
    val USER_ID: TableField<NotificationSettingsRecord, UUID?> = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.notification_settings.channel</code>.
     */
    val CHANNEL: TableField<NotificationSettingsRecord, NotificationChannel?> = createField(DSL.name("channel"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(NotificationChannel::class.java), this, "")

    /**
     * The column <code>public.notification_settings.target</code>.
     */
    val TARGET: TableField<NotificationSettingsRecord, String?> = createField(DSL.name("target"), SQLDataType.VARCHAR.nullable(false), this, "")

    /**
     * The column <code>public.notification_settings.event_type</code>.
     */
    val EVENT_TYPE: TableField<NotificationSettingsRecord, NotificationEvent?> = createField(DSL.name("event_type"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(NotificationEvent::class.java), this, "")

    /**
     * The column <code>public.notification_settings.enabled</code>.
     */
    val ENABLED: TableField<NotificationSettingsRecord, Boolean?> = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "")

    private constructor(alias: Name, aliased: Table<NotificationSettingsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<NotificationSettingsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<NotificationSettingsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.notification_settings</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.notification_settings</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.notification_settings</code> table reference
     */
    constructor(): this(DSL.name("notification_settings"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, NotificationSettingsRecord>?, parentPath: InverseForeignKey<out Record, NotificationSettingsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, NOTIFICATION_SETTINGS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class NotificationSettingsPath : NotificationSettings, Path<NotificationSettingsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, NotificationSettingsRecord>?, parentPath: InverseForeignKey<out Record, NotificationSettingsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<NotificationSettingsRecord>): super(alias, aliased)
        override fun `as`(alias: String): NotificationSettingsPath = NotificationSettingsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): NotificationSettingsPath = NotificationSettingsPath(alias, this)
        override fun `as`(alias: Table<*>): NotificationSettingsPath = NotificationSettingsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<NotificationSettingsRecord> = NOTIFICATION_SETTINGS_PKEY
    override fun getReferences(): List<ForeignKey<NotificationSettingsRecord, *>> = listOf(NOTIFICATION_SETTINGS__NOTIFICATION_SETTINGS_USER_ID_FKEY)

    private lateinit var _users: UsersPath

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    fun users(): UsersPath {
        if (!this::_users.isInitialized)
            _users = UsersPath(this, NOTIFICATION_SETTINGS__NOTIFICATION_SETTINGS_USER_ID_FKEY, null)

        return _users;
    }

    val users: UsersPath
        get(): UsersPath = users()
    override fun `as`(alias: String): NotificationSettings = NotificationSettings(DSL.name(alias), this)
    override fun `as`(alias: Name): NotificationSettings = NotificationSettings(alias, this)
    override fun `as`(alias: Table<*>): NotificationSettings = NotificationSettings(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): NotificationSettings = NotificationSettings(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): NotificationSettings = NotificationSettings(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): NotificationSettings = NotificationSettings(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): NotificationSettings = NotificationSettings(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): NotificationSettings = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): NotificationSettings = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): NotificationSettings = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): NotificationSettings = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): NotificationSettings = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): NotificationSettings = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): NotificationSettings = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): NotificationSettings = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): NotificationSettings = where(DSL.notExists(select))
}
