/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables


import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.example.backend.database.Public
import org.example.backend.database.enums.PhaseType
import org.example.backend.database.indexes.IDX_PHASES_TOURNAMENT
import org.example.backend.database.keys.MATCHES__MATCHES_PHASE_ID_FKEY
import org.example.backend.database.keys.PHASES_PKEY
import org.example.backend.database.keys.PHASES__PHASES_TOURNAMENT_ID_FKEY
import org.example.backend.database.tables.Matches.MatchesPath
import org.example.backend.database.tables.Tournaments.TournamentsPath
import org.example.backend.database.tables.records.PhasesRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Phases(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, PhasesRecord>?,
    parentPath: InverseForeignKey<out Record, PhasesRecord>?,
    aliased: Table<PhasesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<PhasesRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.phases</code>
         */
        val PHASES: Phases = Phases()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PhasesRecord> = PhasesRecord::class.java

    /**
     * The column <code>public.phases.id</code>.
     */
    val ID: TableField<PhasesRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.phases.tournament_id</code>.
     */
    val TOURNAMENT_ID: TableField<PhasesRecord, UUID?> = createField(DSL.name("tournament_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.phases.game</code>.
     */
    val GAME: TableField<PhasesRecord, String?> = createField(DSL.name("game"), SQLDataType.VARCHAR.nullable(false), this, "")

    /**
     * The column <code>public.phases.position</code>.
     */
    val POSITION: TableField<PhasesRecord, Int?> = createField(DSL.name("position"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.phases.type</code>.
     */
    val TYPE: TableField<PhasesRecord, PhaseType?> = createField(DSL.name("type"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(PhaseType::class.java), this, "")

    /**
     * The column <code>public.phases.default_bo</code>.
     */
    val DEFAULT_BO: TableField<PhasesRecord, Int?> = createField(DSL.name("default_bo"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>public.phases.settings</code>.
     */
    val SETTINGS: TableField<PhasesRecord, JSONB?> = createField(DSL.name("settings"), SQLDataType.JSONB, this, "")

    private constructor(alias: Name, aliased: Table<PhasesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<PhasesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<PhasesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.phases</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.phases</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.phases</code> table reference
     */
    constructor(): this(DSL.name("phases"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PhasesRecord>?, parentPath: InverseForeignKey<out Record, PhasesRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, PHASES, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class PhasesPath : Phases, Path<PhasesRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PhasesRecord>?, parentPath: InverseForeignKey<out Record, PhasesRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<PhasesRecord>): super(alias, aliased)
        override fun `as`(alias: String): PhasesPath = PhasesPath(DSL.name(alias), this)
        override fun `as`(alias: Name): PhasesPath = PhasesPath(alias, this)
        override fun `as`(alias: Table<*>): PhasesPath = PhasesPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_PHASES_TOURNAMENT)
    override fun getPrimaryKey(): UniqueKey<PhasesRecord> = PHASES_PKEY
    override fun getReferences(): List<ForeignKey<PhasesRecord, *>> = listOf(PHASES__PHASES_TOURNAMENT_ID_FKEY)

    private lateinit var _tournaments: TournamentsPath

    /**
     * Get the implicit join path to the <code>public.tournaments</code> table.
     */
    fun tournaments(): TournamentsPath {
        if (!this::_tournaments.isInitialized)
            _tournaments = TournamentsPath(this, PHASES__PHASES_TOURNAMENT_ID_FKEY, null)

        return _tournaments;
    }

    val tournaments: TournamentsPath
        get(): TournamentsPath = tournaments()

    private lateinit var _matches: MatchesPath

    /**
     * Get the implicit to-many join path to the <code>public.matches</code>
     * table
     */
    fun matches(): MatchesPath {
        if (!this::_matches.isInitialized)
            _matches = MatchesPath(this, null, MATCHES__MATCHES_PHASE_ID_FKEY.inverseKey)

        return _matches;
    }

    val matches: MatchesPath
        get(): MatchesPath = matches()
    override fun `as`(alias: String): Phases = Phases(DSL.name(alias), this)
    override fun `as`(alias: Name): Phases = Phases(alias, this)
    override fun `as`(alias: Table<*>): Phases = Phases(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Phases = Phases(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Phases = Phases(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Phases = Phases(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Phases = Phases(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Phases = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Phases = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Phases = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Phases = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Phases = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Phases = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Phases = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Phases = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Phases = where(DSL.notExists(select))
}
