/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables


import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.example.backend.database.Public
import org.example.backend.database.keys.MATCHDB__MATCHDB_PLAYER1_ID_FKEY
import org.example.backend.database.keys.MATCHDB__MATCHDB_PLAYER2_ID_FKEY
import org.example.backend.database.keys.MATCHDB__MATCHDB_WINNER_ID_FKEY
import org.example.backend.database.keys.PLAYERDB_PKEY
import org.example.backend.database.keys.PLAYERDB__PLAYERDB_TOURNAMENT_ID_FKEY
import org.example.backend.database.keys.PLAYERDB__PLAYERDB_USER_ID_FKEY
import org.example.backend.database.tables.Matchdb.MatchdbPath
import org.example.backend.database.tables.Playerdb.PlayerdbPath
import org.example.backend.database.tables.Tournamentdb.TournamentdbPath
import org.example.backend.database.tables.records.PlayerdbRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Playerdb(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, PlayerdbRecord>?,
    parentPath: InverseForeignKey<out Record, PlayerdbRecord>?,
    aliased: Table<PlayerdbRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<PlayerdbRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.playerdb</code>
         */
        val PLAYERDB: Playerdb = Playerdb()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PlayerdbRecord> = PlayerdbRecord::class.java

    /**
     * The column <code>public.playerdb.id</code>.
     */
    val ID: TableField<PlayerdbRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.playerdb.user_id</code>.
     */
    val USER_ID: TableField<PlayerdbRecord, Long?> = createField(DSL.name("user_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>public.playerdb.tournament_id</code>.
     */
    val TOURNAMENT_ID: TableField<PlayerdbRecord, Long?> = createField(DSL.name("tournament_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.playerdb.name</code>.
     */
    val NAME: TableField<PlayerdbRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.playerdb.score</code>.
     */
    val SCORE: TableField<PlayerdbRecord, Int?> = createField(DSL.name("score"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>public.playerdb.created_at</code>.
     */
    val CREATED_AT: TableField<PlayerdbRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<PlayerdbRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<PlayerdbRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<PlayerdbRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.playerdb</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.playerdb</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.playerdb</code> table reference
     */
    constructor(): this(DSL.name("playerdb"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PlayerdbRecord>?, parentPath: InverseForeignKey<out Record, PlayerdbRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, PLAYERDB, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class PlayerdbPath : Playerdb, Path<PlayerdbRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PlayerdbRecord>?, parentPath: InverseForeignKey<out Record, PlayerdbRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<PlayerdbRecord>): super(alias, aliased)
        override fun `as`(alias: String): PlayerdbPath = PlayerdbPath(DSL.name(alias), this)
        override fun `as`(alias: Name): PlayerdbPath = PlayerdbPath(alias, this)
        override fun `as`(alias: Table<*>): PlayerdbPath = PlayerdbPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<PlayerdbRecord> = PLAYERDB_PKEY
    override fun getReferences(): List<ForeignKey<PlayerdbRecord, *>> = listOf(PLAYERDB__PLAYERDB_TOURNAMENT_ID_FKEY, PLAYERDB__PLAYERDB_USER_ID_FKEY)

    private lateinit var _tournamentdb: TournamentdbPath

    /**
     * Get the implicit join path to the <code>public.tournamentdb</code> table.
     */
    fun tournamentdb(): TournamentdbPath {
        if (!this::_tournamentdb.isInitialized)
            _tournamentdb = TournamentdbPath(this, PLAYERDB__PLAYERDB_TOURNAMENT_ID_FKEY, null)

        return _tournamentdb;
    }

    val tournamentdb: TournamentdbPath
        get(): TournamentdbPath = tournamentdb()

    private lateinit var _playerdb: PlayerdbPath

    /**
     * Get the implicit join path to the <code>public.playerdb</code> table.
     */
    fun playerdb(): PlayerdbPath {
        if (!this::_playerdb.isInitialized)
            _playerdb = PlayerdbPath(this, PLAYERDB__PLAYERDB_USER_ID_FKEY, null)

        return _playerdb;
    }

    val playerdb: PlayerdbPath
        get(): PlayerdbPath = playerdb()

    private lateinit var _matchdbPlayer1IdFkey: MatchdbPath

    /**
     * Get the implicit to-many join path to the <code>public.matchdb</code>
     * table, via the <code>matchdb_player1_id_fkey</code> key
     */
    fun matchdbPlayer1IdFkey(): MatchdbPath {
        if (!this::_matchdbPlayer1IdFkey.isInitialized)
            _matchdbPlayer1IdFkey = MatchdbPath(this, null, MATCHDB__MATCHDB_PLAYER1_ID_FKEY.inverseKey)

        return _matchdbPlayer1IdFkey;
    }

    val matchdbPlayer1IdFkey: MatchdbPath
        get(): MatchdbPath = matchdbPlayer1IdFkey()

    private lateinit var _matchdbPlayer2IdFkey: MatchdbPath

    /**
     * Get the implicit to-many join path to the <code>public.matchdb</code>
     * table, via the <code>matchdb_player2_id_fkey</code> key
     */
    fun matchdbPlayer2IdFkey(): MatchdbPath {
        if (!this::_matchdbPlayer2IdFkey.isInitialized)
            _matchdbPlayer2IdFkey = MatchdbPath(this, null, MATCHDB__MATCHDB_PLAYER2_ID_FKEY.inverseKey)

        return _matchdbPlayer2IdFkey;
    }

    val matchdbPlayer2IdFkey: MatchdbPath
        get(): MatchdbPath = matchdbPlayer2IdFkey()

    private lateinit var _matchdbWinnerIdFkey: MatchdbPath

    /**
     * Get the implicit to-many join path to the <code>public.matchdb</code>
     * table, via the <code>matchdb_winner_id_fkey</code> key
     */
    fun matchdbWinnerIdFkey(): MatchdbPath {
        if (!this::_matchdbWinnerIdFkey.isInitialized)
            _matchdbWinnerIdFkey = MatchdbPath(this, null, MATCHDB__MATCHDB_WINNER_ID_FKEY.inverseKey)

        return _matchdbWinnerIdFkey;
    }

    val matchdbWinnerIdFkey: MatchdbPath
        get(): MatchdbPath = matchdbWinnerIdFkey()
    override fun `as`(alias: String): Playerdb = Playerdb(DSL.name(alias), this)
    override fun `as`(alias: Name): Playerdb = Playerdb(alias, this)
    override fun `as`(alias: Table<*>): Playerdb = Playerdb(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Playerdb = Playerdb(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Playerdb = Playerdb(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Playerdb = Playerdb(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Playerdb = Playerdb(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Playerdb = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Playerdb = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Playerdb = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Playerdb = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Playerdb = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Playerdb = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Playerdb = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Playerdb = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Playerdb = where(DSL.notExists(select))
}
