/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables


import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.example.backend.database.Public
import org.example.backend.database.enums.RegistrationStatus
import org.example.backend.database.indexes.IDX_REGISTRATIONS_TOURNAMENT
import org.example.backend.database.keys.MATCHES__MATCHES_PARTICIPANT1_ID_FKEY
import org.example.backend.database.keys.MATCHES__MATCHES_PARTICIPANT2_ID_FKEY
import org.example.backend.database.keys.MATCHES__MATCHES_WINNER_ID_FKEY
import org.example.backend.database.keys.REGISTRATIONS_PKEY
import org.example.backend.database.keys.REGISTRATIONS__REGISTRATIONS_TEAM_ID_FKEY
import org.example.backend.database.keys.REGISTRATIONS__REGISTRATIONS_TOURNAMENT_ID_FKEY
import org.example.backend.database.keys.REGISTRATIONS__REGISTRATIONS_USER_ID_FKEY
import org.example.backend.database.keys.REGISTRATION_UNIQUE_TEAM
import org.example.backend.database.keys.REGISTRATION_UNIQUE_USER
import org.example.backend.database.tables.Matches.MatchesPath
import org.example.backend.database.tables.Teams.TeamsPath
import org.example.backend.database.tables.Tournaments.TournamentsPath
import org.example.backend.database.tables.Users.UsersPath
import org.example.backend.database.tables.records.RegistrationsRecord
import org.jooq.Check
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Registrations(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, RegistrationsRecord>?,
    parentPath: InverseForeignKey<out Record, RegistrationsRecord>?,
    aliased: Table<RegistrationsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<RegistrationsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.registrations</code>
         */
        val REGISTRATIONS: Registrations = Registrations()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<RegistrationsRecord> = RegistrationsRecord::class.java

    /**
     * The column <code>public.registrations.id</code>.
     */
    val ID: TableField<RegistrationsRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.registrations.tournament_id</code>.
     */
    val TOURNAMENT_ID: TableField<RegistrationsRecord, UUID?> = createField(DSL.name("tournament_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.registrations.team_id</code>.
     */
    val TEAM_ID: TableField<RegistrationsRecord, UUID?> = createField(DSL.name("team_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.registrations.user_id</code>.
     */
    val USER_ID: TableField<RegistrationsRecord, UUID?> = createField(DSL.name("user_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.registrations.status</code>.
     */
    val STATUS: TableField<RegistrationsRecord, RegistrationStatus?> = createField(DSL.name("status"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field(DSL.raw("'pending'::registration_status"), SQLDataType.VARCHAR)).asEnumDataType(RegistrationStatus::class.java), this, "")

    /**
     * The column <code>public.registrations.seed</code>.
     */
    val SEED: TableField<RegistrationsRecord, Int?> = createField(DSL.name("seed"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.registrations.created_at</code>.
     */
    val CREATED_AT: TableField<RegistrationsRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<RegistrationsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<RegistrationsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<RegistrationsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.registrations</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.registrations</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.registrations</code> table reference
     */
    constructor(): this(DSL.name("registrations"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, RegistrationsRecord>?, parentPath: InverseForeignKey<out Record, RegistrationsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, REGISTRATIONS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class RegistrationsPath : Registrations, Path<RegistrationsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, RegistrationsRecord>?, parentPath: InverseForeignKey<out Record, RegistrationsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<RegistrationsRecord>): super(alias, aliased)
        override fun `as`(alias: String): RegistrationsPath = RegistrationsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): RegistrationsPath = RegistrationsPath(alias, this)
        override fun `as`(alias: Table<*>): RegistrationsPath = RegistrationsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_REGISTRATIONS_TOURNAMENT)
    override fun getPrimaryKey(): UniqueKey<RegistrationsRecord> = REGISTRATIONS_PKEY
    override fun getUniqueKeys(): List<UniqueKey<RegistrationsRecord>> = listOf(REGISTRATION_UNIQUE_TEAM, REGISTRATION_UNIQUE_USER)
    override fun getReferences(): List<ForeignKey<RegistrationsRecord, *>> = listOf(REGISTRATIONS__REGISTRATIONS_TEAM_ID_FKEY, REGISTRATIONS__REGISTRATIONS_TOURNAMENT_ID_FKEY, REGISTRATIONS__REGISTRATIONS_USER_ID_FKEY)

    private lateinit var _teams: TeamsPath

    /**
     * Get the implicit join path to the <code>public.teams</code> table.
     */
    fun teams(): TeamsPath {
        if (!this::_teams.isInitialized)
            _teams = TeamsPath(this, REGISTRATIONS__REGISTRATIONS_TEAM_ID_FKEY, null)

        return _teams;
    }

    val teams: TeamsPath
        get(): TeamsPath = teams()

    private lateinit var _tournaments: TournamentsPath

    /**
     * Get the implicit join path to the <code>public.tournaments</code> table.
     */
    fun tournaments(): TournamentsPath {
        if (!this::_tournaments.isInitialized)
            _tournaments = TournamentsPath(this, REGISTRATIONS__REGISTRATIONS_TOURNAMENT_ID_FKEY, null)

        return _tournaments;
    }

    val tournaments: TournamentsPath
        get(): TournamentsPath = tournaments()

    private lateinit var _users: UsersPath

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    fun users(): UsersPath {
        if (!this::_users.isInitialized)
            _users = UsersPath(this, REGISTRATIONS__REGISTRATIONS_USER_ID_FKEY, null)

        return _users;
    }

    val users: UsersPath
        get(): UsersPath = users()

    private lateinit var _matchesParticipant1IdFkey: MatchesPath

    /**
     * Get the implicit to-many join path to the <code>public.matches</code>
     * table, via the <code>matches_participant1_id_fkey</code> key
     */
    fun matchesParticipant1IdFkey(): MatchesPath {
        if (!this::_matchesParticipant1IdFkey.isInitialized)
            _matchesParticipant1IdFkey = MatchesPath(this, null, MATCHES__MATCHES_PARTICIPANT1_ID_FKEY.inverseKey)

        return _matchesParticipant1IdFkey;
    }

    val matchesParticipant1IdFkey: MatchesPath
        get(): MatchesPath = matchesParticipant1IdFkey()

    private lateinit var _matchesParticipant2IdFkey: MatchesPath

    /**
     * Get the implicit to-many join path to the <code>public.matches</code>
     * table, via the <code>matches_participant2_id_fkey</code> key
     */
    fun matchesParticipant2IdFkey(): MatchesPath {
        if (!this::_matchesParticipant2IdFkey.isInitialized)
            _matchesParticipant2IdFkey = MatchesPath(this, null, MATCHES__MATCHES_PARTICIPANT2_ID_FKEY.inverseKey)

        return _matchesParticipant2IdFkey;
    }

    val matchesParticipant2IdFkey: MatchesPath
        get(): MatchesPath = matchesParticipant2IdFkey()

    private lateinit var _matchesWinnerIdFkey: MatchesPath

    /**
     * Get the implicit to-many join path to the <code>public.matches</code>
     * table, via the <code>matches_winner_id_fkey</code> key
     */
    fun matchesWinnerIdFkey(): MatchesPath {
        if (!this::_matchesWinnerIdFkey.isInitialized)
            _matchesWinnerIdFkey = MatchesPath(this, null, MATCHES__MATCHES_WINNER_ID_FKEY.inverseKey)

        return _matchesWinnerIdFkey;
    }

    val matchesWinnerIdFkey: MatchesPath
        get(): MatchesPath = matchesWinnerIdFkey()
    override fun getChecks(): List<Check<RegistrationsRecord>> = listOf(
        Internal.createCheck(this, DSL.name("registration_one_participant"), "((num_nonnulls(team_id, user_id) = 1))", true)
    )
    override fun `as`(alias: String): Registrations = Registrations(DSL.name(alias), this)
    override fun `as`(alias: Name): Registrations = Registrations(alias, this)
    override fun `as`(alias: Table<*>): Registrations = Registrations(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Registrations = Registrations(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Registrations = Registrations(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Registrations = Registrations(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Registrations = Registrations(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Registrations = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Registrations = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Registrations = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Registrations = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Registrations = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Registrations = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Registrations = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Registrations = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Registrations = where(DSL.notExists(select))
}
