/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables


import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.example.backend.database.Public
import org.example.backend.database.keys.SCORE_REPORTS_PKEY
import org.example.backend.database.keys.SCORE_REPORTS__SCORE_REPORTS_MATCH_ID_FKEY
import org.example.backend.database.keys.SCORE_REPORTS__SCORE_REPORTS_REPORTED_BY_FKEY
import org.example.backend.database.tables.Matches.MatchesPath
import org.example.backend.database.tables.Users.UsersPath
import org.example.backend.database.tables.records.ScoreReportsRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ScoreReports(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ScoreReportsRecord>?,
    parentPath: InverseForeignKey<out Record, ScoreReportsRecord>?,
    aliased: Table<ScoreReportsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ScoreReportsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.score_reports</code>
         */
        val SCORE_REPORTS: ScoreReports = ScoreReports()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ScoreReportsRecord> = ScoreReportsRecord::class.java

    /**
     * The column <code>public.score_reports.id</code>.
     */
    val ID: TableField<ScoreReportsRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.score_reports.match_id</code>.
     */
    val MATCH_ID: TableField<ScoreReportsRecord, UUID?> = createField(DSL.name("match_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.score_reports.reported_by</code>.
     */
    val REPORTED_BY: TableField<ScoreReportsRecord, UUID?> = createField(DSL.name("reported_by"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.score_reports.scores</code>.
     */
    val SCORES: TableField<ScoreReportsRecord, JSONB?> = createField(DSL.name("scores"), SQLDataType.JSONB.nullable(false), this, "")

    /**
     * The column <code>public.score_reports.created_at</code>.
     */
    val CREATED_AT: TableField<ScoreReportsRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<ScoreReportsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ScoreReportsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ScoreReportsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.score_reports</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.score_reports</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.score_reports</code> table reference
     */
    constructor(): this(DSL.name("score_reports"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ScoreReportsRecord>?, parentPath: InverseForeignKey<out Record, ScoreReportsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, SCORE_REPORTS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ScoreReportsPath : ScoreReports, Path<ScoreReportsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ScoreReportsRecord>?, parentPath: InverseForeignKey<out Record, ScoreReportsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<ScoreReportsRecord>): super(alias, aliased)
        override fun `as`(alias: String): ScoreReportsPath = ScoreReportsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): ScoreReportsPath = ScoreReportsPath(alias, this)
        override fun `as`(alias: Table<*>): ScoreReportsPath = ScoreReportsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<ScoreReportsRecord> = SCORE_REPORTS_PKEY
    override fun getReferences(): List<ForeignKey<ScoreReportsRecord, *>> = listOf(SCORE_REPORTS__SCORE_REPORTS_MATCH_ID_FKEY, SCORE_REPORTS__SCORE_REPORTS_REPORTED_BY_FKEY)

    private lateinit var _matches: MatchesPath

    /**
     * Get the implicit join path to the <code>public.matches</code> table.
     */
    fun matches(): MatchesPath {
        if (!this::_matches.isInitialized)
            _matches = MatchesPath(this, SCORE_REPORTS__SCORE_REPORTS_MATCH_ID_FKEY, null)

        return _matches;
    }

    val matches: MatchesPath
        get(): MatchesPath = matches()

    private lateinit var _users: UsersPath

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    fun users(): UsersPath {
        if (!this::_users.isInitialized)
            _users = UsersPath(this, SCORE_REPORTS__SCORE_REPORTS_REPORTED_BY_FKEY, null)

        return _users;
    }

    val users: UsersPath
        get(): UsersPath = users()
    override fun `as`(alias: String): ScoreReports = ScoreReports(DSL.name(alias), this)
    override fun `as`(alias: Name): ScoreReports = ScoreReports(alias, this)
    override fun `as`(alias: Table<*>): ScoreReports = ScoreReports(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ScoreReports = ScoreReports(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ScoreReports = ScoreReports(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ScoreReports = ScoreReports(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ScoreReports = ScoreReports(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ScoreReports = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ScoreReports = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ScoreReports = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): ScoreReports = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): ScoreReports = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ScoreReports = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ScoreReports = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ScoreReports = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ScoreReports = where(DSL.notExists(select))
}
