/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables


import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.example.backend.database.Public
import org.example.backend.database.enums.TeamMemberRole
import org.example.backend.database.indexes.IDX_TEAM_MEMBERS_USER
import org.example.backend.database.keys.TEAM_MEMBERS_PKEY
import org.example.backend.database.keys.TEAM_MEMBERS__TEAM_MEMBERS_TEAM_ID_FKEY
import org.example.backend.database.keys.TEAM_MEMBERS__TEAM_MEMBERS_USER_ID_FKEY
import org.example.backend.database.tables.Teams.TeamsPath
import org.example.backend.database.tables.Users.UsersPath
import org.example.backend.database.tables.records.TeamMembersRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TeamMembers(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TeamMembersRecord>?,
    parentPath: InverseForeignKey<out Record, TeamMembersRecord>?,
    aliased: Table<TeamMembersRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TeamMembersRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.team_members</code>
         */
        val TEAM_MEMBERS: TeamMembers = TeamMembers()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TeamMembersRecord> = TeamMembersRecord::class.java

    /**
     * The column <code>public.team_members.team_id</code>.
     */
    val TEAM_ID: TableField<TeamMembersRecord, UUID?> = createField(DSL.name("team_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.team_members.user_id</code>.
     */
    val USER_ID: TableField<TeamMembersRecord, UUID?> = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.team_members.role</code>.
     */
    val ROLE: TableField<TeamMembersRecord, TeamMemberRole?> = createField(DSL.name("role"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field(DSL.raw("'member'::team_member_role"), SQLDataType.VARCHAR)).asEnumDataType(TeamMemberRole::class.java), this, "")

    /**
     * The column <code>public.team_members.joined_at</code>.
     */
    val JOINED_AT: TableField<TeamMembersRecord, OffsetDateTime?> = createField(DSL.name("joined_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<TeamMembersRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TeamMembersRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TeamMembersRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.team_members</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.team_members</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.team_members</code> table reference
     */
    constructor(): this(DSL.name("team_members"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, TeamMembersRecord>?, parentPath: InverseForeignKey<out Record, TeamMembersRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, TEAM_MEMBERS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class TeamMembersPath : TeamMembers, Path<TeamMembersRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, TeamMembersRecord>?, parentPath: InverseForeignKey<out Record, TeamMembersRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<TeamMembersRecord>): super(alias, aliased)
        override fun `as`(alias: String): TeamMembersPath = TeamMembersPath(DSL.name(alias), this)
        override fun `as`(alias: Name): TeamMembersPath = TeamMembersPath(alias, this)
        override fun `as`(alias: Table<*>): TeamMembersPath = TeamMembersPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_TEAM_MEMBERS_USER)
    override fun getPrimaryKey(): UniqueKey<TeamMembersRecord> = TEAM_MEMBERS_PKEY
    override fun getReferences(): List<ForeignKey<TeamMembersRecord, *>> = listOf(TEAM_MEMBERS__TEAM_MEMBERS_TEAM_ID_FKEY, TEAM_MEMBERS__TEAM_MEMBERS_USER_ID_FKEY)

    private lateinit var _teams: TeamsPath

    /**
     * Get the implicit join path to the <code>public.teams</code> table.
     */
    fun teams(): TeamsPath {
        if (!this::_teams.isInitialized)
            _teams = TeamsPath(this, TEAM_MEMBERS__TEAM_MEMBERS_TEAM_ID_FKEY, null)

        return _teams;
    }

    val teams: TeamsPath
        get(): TeamsPath = teams()

    private lateinit var _users: UsersPath

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    fun users(): UsersPath {
        if (!this::_users.isInitialized)
            _users = UsersPath(this, TEAM_MEMBERS__TEAM_MEMBERS_USER_ID_FKEY, null)

        return _users;
    }

    val users: UsersPath
        get(): UsersPath = users()
    override fun `as`(alias: String): TeamMembers = TeamMembers(DSL.name(alias), this)
    override fun `as`(alias: Name): TeamMembers = TeamMembers(alias, this)
    override fun `as`(alias: Table<*>): TeamMembers = TeamMembers(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TeamMembers = TeamMembers(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TeamMembers = TeamMembers(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TeamMembers = TeamMembers(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): TeamMembers = TeamMembers(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): TeamMembers = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): TeamMembers = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): TeamMembers = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): TeamMembers = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): TeamMembers = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): TeamMembers = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): TeamMembers = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): TeamMembers = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): TeamMembers = where(DSL.notExists(select))
}
