/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables


import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.example.backend.database.Public
import org.example.backend.database.keys.REGISTRATIONS__REGISTRATIONS_TEAM_ID_FKEY
import org.example.backend.database.keys.TEAMS_PKEY
import org.example.backend.database.keys.TEAMS__TEAMS_CREATED_BY_FKEY
import org.example.backend.database.keys.TEAM_MEMBERS__TEAM_MEMBERS_TEAM_ID_FKEY
import org.example.backend.database.tables.Registrations.RegistrationsPath
import org.example.backend.database.tables.TeamMembers.TeamMembersPath
import org.example.backend.database.tables.Tournaments.TournamentsPath
import org.example.backend.database.tables.Users.UsersPath
import org.example.backend.database.tables.records.TeamsRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Teams(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TeamsRecord>?,
    parentPath: InverseForeignKey<out Record, TeamsRecord>?,
    aliased: Table<TeamsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TeamsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.teams</code>
         */
        val TEAMS: Teams = Teams()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TeamsRecord> = TeamsRecord::class.java

    /**
     * The column <code>public.teams.id</code>.
     */
    val ID: TableField<TeamsRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.teams.name</code>.
     */
    val NAME: TableField<TeamsRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR.nullable(false), this, "")

    /**
     * The column <code>public.teams.tag</code>.
     */
    val TAG: TableField<TeamsRecord, String?> = createField(DSL.name("tag"), SQLDataType.VARCHAR(8), this, "")

    /**
     * The column <code>public.teams.logo_url</code>.
     */
    val LOGO_URL: TableField<TeamsRecord, String?> = createField(DSL.name("logo_url"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>public.teams.created_by</code>.
     */
    val CREATED_BY: TableField<TeamsRecord, UUID?> = createField(DSL.name("created_by"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.teams.created_at</code>.
     */
    val CREATED_AT: TableField<TeamsRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<TeamsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TeamsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TeamsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.teams</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.teams</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.teams</code> table reference
     */
    constructor(): this(DSL.name("teams"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, TeamsRecord>?, parentPath: InverseForeignKey<out Record, TeamsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, TEAMS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class TeamsPath : Teams, Path<TeamsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, TeamsRecord>?, parentPath: InverseForeignKey<out Record, TeamsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<TeamsRecord>): super(alias, aliased)
        override fun `as`(alias: String): TeamsPath = TeamsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): TeamsPath = TeamsPath(alias, this)
        override fun `as`(alias: Table<*>): TeamsPath = TeamsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<TeamsRecord> = TEAMS_PKEY
    override fun getReferences(): List<ForeignKey<TeamsRecord, *>> = listOf(TEAMS__TEAMS_CREATED_BY_FKEY)

    private lateinit var _users: UsersPath

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    fun users(): UsersPath {
        if (!this::_users.isInitialized)
            _users = UsersPath(this, TEAMS__TEAMS_CREATED_BY_FKEY, null)

        return _users;
    }

    val users: UsersPath
        get(): UsersPath = users()

    private lateinit var _registrations: RegistrationsPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.registrations</code> table
     */
    fun registrations(): RegistrationsPath {
        if (!this::_registrations.isInitialized)
            _registrations = RegistrationsPath(this, null, REGISTRATIONS__REGISTRATIONS_TEAM_ID_FKEY.inverseKey)

        return _registrations;
    }

    val registrations: RegistrationsPath
        get(): RegistrationsPath = registrations()

    private lateinit var _teamMembers: TeamMembersPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.team_members</code> table
     */
    fun teamMembers(): TeamMembersPath {
        if (!this::_teamMembers.isInitialized)
            _teamMembers = TeamMembersPath(this, null, TEAM_MEMBERS__TEAM_MEMBERS_TEAM_ID_FKEY.inverseKey)

        return _teamMembers;
    }

    val teamMembers: TeamMembersPath
        get(): TeamMembersPath = teamMembers()

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.tournaments</code> table
     */
    val tournaments: TournamentsPath
        get(): TournamentsPath = registrations().tournaments()
    override fun `as`(alias: String): Teams = Teams(DSL.name(alias), this)
    override fun `as`(alias: Name): Teams = Teams(alias, this)
    override fun `as`(alias: Table<*>): Teams = Teams(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Teams = Teams(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Teams = Teams(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Teams = Teams(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Teams = Teams(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Teams = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Teams = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Teams = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Teams = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Teams = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Teams = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Teams = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Teams = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Teams = where(DSL.notExists(select))
}
