/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables


import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.example.backend.database.Public
import org.example.backend.database.enums.TournamentStatus
import org.example.backend.database.enums.TournamentVisibility
import org.example.backend.database.keys.PHASES__PHASES_TOURNAMENT_ID_FKEY
import org.example.backend.database.keys.REGISTRATIONS__REGISTRATIONS_TOURNAMENT_ID_FKEY
import org.example.backend.database.keys.TOURNAMENTS_PKEY
import org.example.backend.database.keys.TOURNAMENT_ORGANIZERS__TOURNAMENT_ORGANIZERS_TOURNAMENT_ID_FKEY
import org.example.backend.database.tables.Phases.PhasesPath
import org.example.backend.database.tables.Registrations.RegistrationsPath
import org.example.backend.database.tables.Teams.TeamsPath
import org.example.backend.database.tables.TournamentOrganizers.TournamentOrganizersPath
import org.example.backend.database.tables.Users.UsersPath
import org.example.backend.database.tables.records.TournamentsRecord
import org.jooq.Check
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Tournaments(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TournamentsRecord>?,
    parentPath: InverseForeignKey<out Record, TournamentsRecord>?,
    aliased: Table<TournamentsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TournamentsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.tournaments</code>
         */
        val TOURNAMENTS: Tournaments = Tournaments()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TournamentsRecord> = TournamentsRecord::class.java

    /**
     * The column <code>public.tournaments.id</code>.
     */
    val ID: TableField<TournamentsRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.tournaments.name</code>.
     */
    val NAME: TableField<TournamentsRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR.nullable(false), this, "")

    /**
     * The column <code>public.tournaments.description</code>.
     */
    val DESCRIPTION: TableField<TournamentsRecord, String?> = createField(DSL.name("description"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.tournaments.visibility</code>.
     */
    val VISIBILITY: TableField<TournamentsRecord, TournamentVisibility?> = createField(DSL.name("visibility"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field(DSL.raw("'public'::tournament_visibility"), SQLDataType.VARCHAR)).asEnumDataType(TournamentVisibility::class.java), this, "")

    /**
     * The column <code>public.tournaments.status</code>.
     */
    val STATUS: TableField<TournamentsRecord, TournamentStatus?> = createField(DSL.name("status"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field(DSL.raw("'draft'::tournament_status"), SQLDataType.VARCHAR)).asEnumDataType(TournamentStatus::class.java), this, "")

    /**
     * The column <code>public.tournaments.team_size</code>.
     */
    val TEAM_SIZE: TableField<TournamentsRecord, Int?> = createField(DSL.name("team_size"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>public.tournaments.max_participants</code>.
     */
    val MAX_PARTICIPANTS: TableField<TournamentsRecord, Int?> = createField(DSL.name("max_participants"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.tournaments.check_in_required</code>.
     */
    val CHECK_IN_REQUIRED: TableField<TournamentsRecord, Boolean?> = createField(DSL.name("check_in_required"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    /**
     * The column <code>public.tournaments.check_in_window_minutes</code>.
     */
    val CHECK_IN_WINDOW_MINUTES: TableField<TournamentsRecord, Int?> = createField(DSL.name("check_in_window_minutes"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.tournaments.registration_open_at</code>.
     */
    val REGISTRATION_OPEN_AT: TableField<TournamentsRecord, OffsetDateTime?> = createField(DSL.name("registration_open_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.tournaments.registration_close_at</code>.
     */
    val REGISTRATION_CLOSE_AT: TableField<TournamentsRecord, OffsetDateTime?> = createField(DSL.name("registration_close_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.tournaments.start_at</code>.
     */
    val START_AT: TableField<TournamentsRecord, OffsetDateTime?> = createField(DSL.name("start_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.tournaments.end_at</code>.
     */
    val END_AT: TableField<TournamentsRecord, OffsetDateTime?> = createField(DSL.name("end_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

    /**
     * The column <code>public.tournaments.created_at</code>.
     */
    val CREATED_AT: TableField<TournamentsRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.tournaments.file_template</code>.
     */
    val FILE_TEMPLATE: TableField<TournamentsRecord, String?> = createField(DSL.name("file_template"), SQLDataType.VARCHAR, this, "")

    private constructor(alias: Name, aliased: Table<TournamentsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TournamentsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TournamentsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.tournaments</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.tournaments</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.tournaments</code> table reference
     */
    constructor(): this(DSL.name("tournaments"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, TournamentsRecord>?, parentPath: InverseForeignKey<out Record, TournamentsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, TOURNAMENTS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class TournamentsPath : Tournaments, Path<TournamentsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, TournamentsRecord>?, parentPath: InverseForeignKey<out Record, TournamentsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<TournamentsRecord>): super(alias, aliased)
        override fun `as`(alias: String): TournamentsPath = TournamentsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): TournamentsPath = TournamentsPath(alias, this)
        override fun `as`(alias: Table<*>): TournamentsPath = TournamentsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<TournamentsRecord> = TOURNAMENTS_PKEY

    private lateinit var _phases: PhasesPath

    /**
     * Get the implicit to-many join path to the <code>public.phases</code>
     * table
     */
    fun phases(): PhasesPath {
        if (!this::_phases.isInitialized)
            _phases = PhasesPath(this, null, PHASES__PHASES_TOURNAMENT_ID_FKEY.inverseKey)

        return _phases;
    }

    val phases: PhasesPath
        get(): PhasesPath = phases()

    private lateinit var _registrations: RegistrationsPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.registrations</code> table
     */
    fun registrations(): RegistrationsPath {
        if (!this::_registrations.isInitialized)
            _registrations = RegistrationsPath(this, null, REGISTRATIONS__REGISTRATIONS_TOURNAMENT_ID_FKEY.inverseKey)

        return _registrations;
    }

    val registrations: RegistrationsPath
        get(): RegistrationsPath = registrations()

    private lateinit var _tournamentOrganizers: TournamentOrganizersPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.tournament_organizers</code> table
     */
    fun tournamentOrganizers(): TournamentOrganizersPath {
        if (!this::_tournamentOrganizers.isInitialized)
            _tournamentOrganizers = TournamentOrganizersPath(this, null, TOURNAMENT_ORGANIZERS__TOURNAMENT_ORGANIZERS_TOURNAMENT_ID_FKEY.inverseKey)

        return _tournamentOrganizers;
    }

    val tournamentOrganizers: TournamentOrganizersPath
        get(): TournamentOrganizersPath = tournamentOrganizers()

    /**
     * Get the implicit many-to-many join path to the <code>public.teams</code>
     * table
     */
    val teams: TeamsPath
        get(): TeamsPath = registrations().teams()

    /**
     * Get the implicit many-to-many join path to the <code>public.users</code>
     * table, via the <code>registrations_user_id_fkey</code> key
     */
    val registrationsUserIdFkey: UsersPath
        get(): UsersPath = registrations().users()

    /**
     * Get the implicit many-to-many join path to the <code>public.users</code>
     * table, via the <code>tournament_organizers_user_id_fkey</code> key
     */
    val tournamentOrganizersUserIdFkey: UsersPath
        get(): UsersPath = tournamentOrganizers().users()
    override fun getChecks(): List<Check<TournamentsRecord>> = listOf(
        Internal.createCheck(this, DSL.name("tournaments_file_template_connu"), "(((file_template IS NULL) OR ((file_template)::text = ANY ((ARRAY['esport_5v5'::character varying, 'football_11v11'::character varying])::text[]))))", true)
    )
    override fun `as`(alias: String): Tournaments = Tournaments(DSL.name(alias), this)
    override fun `as`(alias: Name): Tournaments = Tournaments(alias, this)
    override fun `as`(alias: Table<*>): Tournaments = Tournaments(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Tournaments = Tournaments(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Tournaments = Tournaments(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Tournaments = Tournaments(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Tournaments = Tournaments(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Tournaments = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Tournaments = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Tournaments = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Tournaments = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Tournaments = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Tournaments = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Tournaments = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Tournaments = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Tournaments = where(DSL.notExists(select))
}
