/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables


import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.example.backend.database.Public
import org.example.backend.database.enums.OrganizerRole
import org.example.backend.database.keys.TOURNAMENT_ORGANIZERS_PKEY
import org.example.backend.database.keys.TOURNAMENT_ORGANIZERS__TOURNAMENT_ORGANIZERS_TOURNAMENT_ID_FKEY
import org.example.backend.database.keys.TOURNAMENT_ORGANIZERS__TOURNAMENT_ORGANIZERS_USER_ID_FKEY
import org.example.backend.database.tables.Tournaments.TournamentsPath
import org.example.backend.database.tables.Users.UsersPath
import org.example.backend.database.tables.records.TournamentOrganizersRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TournamentOrganizers(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TournamentOrganizersRecord>?,
    parentPath: InverseForeignKey<out Record, TournamentOrganizersRecord>?,
    aliased: Table<TournamentOrganizersRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TournamentOrganizersRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.tournament_organizers</code>
         */
        val TOURNAMENT_ORGANIZERS: TournamentOrganizers = TournamentOrganizers()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TournamentOrganizersRecord> = TournamentOrganizersRecord::class.java

    /**
     * The column <code>public.tournament_organizers.tournament_id</code>.
     */
    val TOURNAMENT_ID: TableField<TournamentOrganizersRecord, UUID?> = createField(DSL.name("tournament_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.tournament_organizers.user_id</code>.
     */
    val USER_ID: TableField<TournamentOrganizersRecord, UUID?> = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.tournament_organizers.role</code>.
     */
    val ROLE: TableField<TournamentOrganizersRecord, OrganizerRole?> = createField(DSL.name("role"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field(DSL.raw("'co_organizer'::organizer_role"), SQLDataType.VARCHAR)).asEnumDataType(OrganizerRole::class.java), this, "")

    private constructor(alias: Name, aliased: Table<TournamentOrganizersRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TournamentOrganizersRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TournamentOrganizersRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.tournament_organizers</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.tournament_organizers</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.tournament_organizers</code> table reference
     */
    constructor(): this(DSL.name("tournament_organizers"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, TournamentOrganizersRecord>?, parentPath: InverseForeignKey<out Record, TournamentOrganizersRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, TOURNAMENT_ORGANIZERS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class TournamentOrganizersPath : TournamentOrganizers, Path<TournamentOrganizersRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, TournamentOrganizersRecord>?, parentPath: InverseForeignKey<out Record, TournamentOrganizersRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<TournamentOrganizersRecord>): super(alias, aliased)
        override fun `as`(alias: String): TournamentOrganizersPath = TournamentOrganizersPath(DSL.name(alias), this)
        override fun `as`(alias: Name): TournamentOrganizersPath = TournamentOrganizersPath(alias, this)
        override fun `as`(alias: Table<*>): TournamentOrganizersPath = TournamentOrganizersPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<TournamentOrganizersRecord> = TOURNAMENT_ORGANIZERS_PKEY
    override fun getReferences(): List<ForeignKey<TournamentOrganizersRecord, *>> = listOf(TOURNAMENT_ORGANIZERS__TOURNAMENT_ORGANIZERS_TOURNAMENT_ID_FKEY, TOURNAMENT_ORGANIZERS__TOURNAMENT_ORGANIZERS_USER_ID_FKEY)

    private lateinit var _tournaments: TournamentsPath

    /**
     * Get the implicit join path to the <code>public.tournaments</code> table.
     */
    fun tournaments(): TournamentsPath {
        if (!this::_tournaments.isInitialized)
            _tournaments = TournamentsPath(this, TOURNAMENT_ORGANIZERS__TOURNAMENT_ORGANIZERS_TOURNAMENT_ID_FKEY, null)

        return _tournaments;
    }

    val tournaments: TournamentsPath
        get(): TournamentsPath = tournaments()

    private lateinit var _users: UsersPath

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    fun users(): UsersPath {
        if (!this::_users.isInitialized)
            _users = UsersPath(this, TOURNAMENT_ORGANIZERS__TOURNAMENT_ORGANIZERS_USER_ID_FKEY, null)

        return _users;
    }

    val users: UsersPath
        get(): UsersPath = users()
    override fun `as`(alias: String): TournamentOrganizers = TournamentOrganizers(DSL.name(alias), this)
    override fun `as`(alias: Name): TournamentOrganizers = TournamentOrganizers(alias, this)
    override fun `as`(alias: Table<*>): TournamentOrganizers = TournamentOrganizers(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TournamentOrganizers = TournamentOrganizers(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TournamentOrganizers = TournamentOrganizers(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TournamentOrganizers = TournamentOrganizers(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): TournamentOrganizers = TournamentOrganizers(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): TournamentOrganizers = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): TournamentOrganizers = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): TournamentOrganizers = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): TournamentOrganizers = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): TournamentOrganizers = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): TournamentOrganizers = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): TournamentOrganizers = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): TournamentOrganizers = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): TournamentOrganizers = where(DSL.notExists(select))
}
