/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables


import java.time.LocalDate

import kotlin.collections.Collection

import org.example.backend.database.Public
import org.example.backend.database.keys.MATCHDB__MATCHDB_TOURNAMENT_ID_FKEY
import org.example.backend.database.keys.PLAYERDB__PLAYERDB_TOURNAMENT_ID_FKEY
import org.example.backend.database.keys.TOURNAMENTDB_PKEY
import org.example.backend.database.tables.Matchdb.MatchdbPath
import org.example.backend.database.tables.Playerdb.PlayerdbPath
import org.example.backend.database.tables.records.TournamentdbRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Tournamentdb(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TournamentdbRecord>?,
    parentPath: InverseForeignKey<out Record, TournamentdbRecord>?,
    aliased: Table<TournamentdbRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TournamentdbRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.tournamentdb</code>
         */
        val TOURNAMENTDB: Tournamentdb = Tournamentdb()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TournamentdbRecord> = TournamentdbRecord::class.java

    /**
     * The column <code>public.tournamentdb.id</code>.
     */
    val ID: TableField<TournamentdbRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.tournamentdb.name</code>.
     */
    val NAME: TableField<TournamentdbRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.tournamentdb.start_date</code>.
     */
    val START_DATE: TableField<TournamentdbRecord, LocalDate?> = createField(DSL.name("start_date"), SQLDataType.LOCALDATE, this, "")

    /**
     * The column <code>public.tournamentdb.end_date</code>.
     */
    val END_DATE: TableField<TournamentdbRecord, LocalDate?> = createField(DSL.name("end_date"), SQLDataType.LOCALDATE, this, "")

    /**
     * The column <code>public.tournamentdb.max_players</code>.
     */
    val MAX_PLAYERS: TableField<TournamentdbRecord, Int?> = createField(DSL.name("max_players"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.tournamentdb.status</code>.
     */
    val STATUS: TableField<TournamentdbRecord, String?> = createField(DSL.name("status"), SQLDataType.VARCHAR(20).defaultValue(DSL.field(DSL.raw("'PENDING'::character varying"), SQLDataType.VARCHAR)), this, "")

    private constructor(alias: Name, aliased: Table<TournamentdbRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TournamentdbRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TournamentdbRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.tournamentdb</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.tournamentdb</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.tournamentdb</code> table reference
     */
    constructor(): this(DSL.name("tournamentdb"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, TournamentdbRecord>?, parentPath: InverseForeignKey<out Record, TournamentdbRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, TOURNAMENTDB, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class TournamentdbPath : Tournamentdb, Path<TournamentdbRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, TournamentdbRecord>?, parentPath: InverseForeignKey<out Record, TournamentdbRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<TournamentdbRecord>): super(alias, aliased)
        override fun `as`(alias: String): TournamentdbPath = TournamentdbPath(DSL.name(alias), this)
        override fun `as`(alias: Name): TournamentdbPath = TournamentdbPath(alias, this)
        override fun `as`(alias: Table<*>): TournamentdbPath = TournamentdbPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<TournamentdbRecord> = TOURNAMENTDB_PKEY

    private lateinit var _matchdb: MatchdbPath

    /**
     * Get the implicit to-many join path to the <code>public.matchdb</code>
     * table
     */
    fun matchdb(): MatchdbPath {
        if (!this::_matchdb.isInitialized)
            _matchdb = MatchdbPath(this, null, MATCHDB__MATCHDB_TOURNAMENT_ID_FKEY.inverseKey)

        return _matchdb;
    }

    val matchdb: MatchdbPath
        get(): MatchdbPath = matchdb()

    private lateinit var _playerdb: PlayerdbPath

    /**
     * Get the implicit to-many join path to the <code>public.playerdb</code>
     * table
     */
    fun playerdb(): PlayerdbPath {
        if (!this::_playerdb.isInitialized)
            _playerdb = PlayerdbPath(this, null, PLAYERDB__PLAYERDB_TOURNAMENT_ID_FKEY.inverseKey)

        return _playerdb;
    }

    val playerdb: PlayerdbPath
        get(): PlayerdbPath = playerdb()
    override fun `as`(alias: String): Tournamentdb = Tournamentdb(DSL.name(alias), this)
    override fun `as`(alias: Name): Tournamentdb = Tournamentdb(alias, this)
    override fun `as`(alias: Table<*>): Tournamentdb = Tournamentdb(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Tournamentdb = Tournamentdb(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Tournamentdb = Tournamentdb(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Tournamentdb = Tournamentdb(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Tournamentdb = Tournamentdb(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Tournamentdb = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Tournamentdb = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Tournamentdb = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Tournamentdb = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Tournamentdb = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Tournamentdb = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Tournamentdb = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Tournamentdb = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Tournamentdb = where(DSL.notExists(select))
}
