/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables


import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.example.backend.database.Public
import org.example.backend.database.keys.DISPUTES__DISPUTES_OPENED_BY_FKEY
import org.example.backend.database.keys.DISPUTES__DISPUTES_RESOLVED_BY_FKEY
import org.example.backend.database.keys.GAME_ACCOUNTS__GAME_ACCOUNTS_USER_ID_FKEY
import org.example.backend.database.keys.JOBS__JOBS_CREATED_BY_FKEY
import org.example.backend.database.keys.NOTIFICATION_SETTINGS__NOTIFICATION_SETTINGS_USER_ID_FKEY
import org.example.backend.database.keys.REGISTRATIONS__REGISTRATIONS_USER_ID_FKEY
import org.example.backend.database.keys.SCORE_REPORTS__SCORE_REPORTS_REPORTED_BY_FKEY
import org.example.backend.database.keys.TEAMS__TEAMS_CREATED_BY_FKEY
import org.example.backend.database.keys.TEAM_MEMBERS__TEAM_MEMBERS_USER_ID_FKEY
import org.example.backend.database.keys.TOURNAMENT_ORGANIZERS__TOURNAMENT_ORGANIZERS_USER_ID_FKEY
import org.example.backend.database.keys.USERS_EMAIL_KEY
import org.example.backend.database.keys.USERS_KEYCLOAK_ID_KEY
import org.example.backend.database.keys.USERS_PKEY
import org.example.backend.database.tables.Disputes.DisputesPath
import org.example.backend.database.tables.GameAccounts.GameAccountsPath
import org.example.backend.database.tables.Jobs.JobsPath
import org.example.backend.database.tables.NotificationSettings.NotificationSettingsPath
import org.example.backend.database.tables.Registrations.RegistrationsPath
import org.example.backend.database.tables.ScoreReports.ScoreReportsPath
import org.example.backend.database.tables.TeamMembers.TeamMembersPath
import org.example.backend.database.tables.Teams.TeamsPath
import org.example.backend.database.tables.TournamentOrganizers.TournamentOrganizersPath
import org.example.backend.database.tables.Tournaments.TournamentsPath
import org.example.backend.database.tables.records.UsersRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Users(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, UsersRecord>?,
    parentPath: InverseForeignKey<out Record, UsersRecord>?,
    aliased: Table<UsersRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<UsersRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.users</code>
         */
        val USERS: Users = Users()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UsersRecord> = UsersRecord::class.java

    /**
     * The column <code>public.users.id</code>.
     */
    val ID: TableField<UsersRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.users.keycloak_id</code>.
     */
    val KEYCLOAK_ID: TableField<UsersRecord, String?> = createField(DSL.name("keycloak_id"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>public.users.pseudo</code>.
     */
    val PSEUDO: TableField<UsersRecord, String?> = createField(DSL.name("pseudo"), SQLDataType.VARCHAR.nullable(false), this, "")

    /**
     * The column <code>public.users.email</code>.
     */
    val EMAIL: TableField<UsersRecord, String?> = createField(DSL.name("email"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>public.users.created_at</code>.
     */
    val CREATED_AT: TableField<UsersRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.users.avatar_url</code>.
     */
    val AVATAR_URL: TableField<UsersRecord, String?> = createField(DSL.name("avatar_url"), SQLDataType.CLOB, this, "")

    private constructor(alias: Name, aliased: Table<UsersRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<UsersRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<UsersRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.users</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.users</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.users</code> table reference
     */
    constructor(): this(DSL.name("users"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UsersRecord>?, parentPath: InverseForeignKey<out Record, UsersRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, USERS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class UsersPath : Users, Path<UsersRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UsersRecord>?, parentPath: InverseForeignKey<out Record, UsersRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<UsersRecord>): super(alias, aliased)
        override fun `as`(alias: String): UsersPath = UsersPath(DSL.name(alias), this)
        override fun `as`(alias: Name): UsersPath = UsersPath(alias, this)
        override fun `as`(alias: Table<*>): UsersPath = UsersPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<UsersRecord> = USERS_PKEY
    override fun getUniqueKeys(): List<UniqueKey<UsersRecord>> = listOf(USERS_EMAIL_KEY, USERS_KEYCLOAK_ID_KEY)

    private lateinit var _disputesOpenedByFkey: DisputesPath

    /**
     * Get the implicit to-many join path to the <code>public.disputes</code>
     * table, via the <code>disputes_opened_by_fkey</code> key
     */
    fun disputesOpenedByFkey(): DisputesPath {
        if (!this::_disputesOpenedByFkey.isInitialized)
            _disputesOpenedByFkey = DisputesPath(this, null, DISPUTES__DISPUTES_OPENED_BY_FKEY.inverseKey)

        return _disputesOpenedByFkey;
    }

    val disputesOpenedByFkey: DisputesPath
        get(): DisputesPath = disputesOpenedByFkey()

    private lateinit var _disputesResolvedByFkey: DisputesPath

    /**
     * Get the implicit to-many join path to the <code>public.disputes</code>
     * table, via the <code>disputes_resolved_by_fkey</code> key
     */
    fun disputesResolvedByFkey(): DisputesPath {
        if (!this::_disputesResolvedByFkey.isInitialized)
            _disputesResolvedByFkey = DisputesPath(this, null, DISPUTES__DISPUTES_RESOLVED_BY_FKEY.inverseKey)

        return _disputesResolvedByFkey;
    }

    val disputesResolvedByFkey: DisputesPath
        get(): DisputesPath = disputesResolvedByFkey()

    private lateinit var _gameAccounts: GameAccountsPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.game_accounts</code> table
     */
    fun gameAccounts(): GameAccountsPath {
        if (!this::_gameAccounts.isInitialized)
            _gameAccounts = GameAccountsPath(this, null, GAME_ACCOUNTS__GAME_ACCOUNTS_USER_ID_FKEY.inverseKey)

        return _gameAccounts;
    }

    val gameAccounts: GameAccountsPath
        get(): GameAccountsPath = gameAccounts()

    private lateinit var _jobs: JobsPath

    /**
     * Get the implicit to-many join path to the <code>public.jobs</code> table
     */
    fun jobs(): JobsPath {
        if (!this::_jobs.isInitialized)
            _jobs = JobsPath(this, null, JOBS__JOBS_CREATED_BY_FKEY.inverseKey)

        return _jobs;
    }

    val jobs: JobsPath
        get(): JobsPath = jobs()

    private lateinit var _notificationSettings: NotificationSettingsPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.notification_settings</code> table
     */
    fun notificationSettings(): NotificationSettingsPath {
        if (!this::_notificationSettings.isInitialized)
            _notificationSettings = NotificationSettingsPath(this, null, NOTIFICATION_SETTINGS__NOTIFICATION_SETTINGS_USER_ID_FKEY.inverseKey)

        return _notificationSettings;
    }

    val notificationSettings: NotificationSettingsPath
        get(): NotificationSettingsPath = notificationSettings()

    private lateinit var _registrations: RegistrationsPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.registrations</code> table
     */
    fun registrations(): RegistrationsPath {
        if (!this::_registrations.isInitialized)
            _registrations = RegistrationsPath(this, null, REGISTRATIONS__REGISTRATIONS_USER_ID_FKEY.inverseKey)

        return _registrations;
    }

    val registrations: RegistrationsPath
        get(): RegistrationsPath = registrations()

    private lateinit var _scoreReports: ScoreReportsPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.score_reports</code> table
     */
    fun scoreReports(): ScoreReportsPath {
        if (!this::_scoreReports.isInitialized)
            _scoreReports = ScoreReportsPath(this, null, SCORE_REPORTS__SCORE_REPORTS_REPORTED_BY_FKEY.inverseKey)

        return _scoreReports;
    }

    val scoreReports: ScoreReportsPath
        get(): ScoreReportsPath = scoreReports()

    private lateinit var _teamMembers: TeamMembersPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.team_members</code> table
     */
    fun teamMembers(): TeamMembersPath {
        if (!this::_teamMembers.isInitialized)
            _teamMembers = TeamMembersPath(this, null, TEAM_MEMBERS__TEAM_MEMBERS_USER_ID_FKEY.inverseKey)

        return _teamMembers;
    }

    val teamMembers: TeamMembersPath
        get(): TeamMembersPath = teamMembers()

    private lateinit var _teams: TeamsPath

    /**
     * Get the implicit to-many join path to the <code>public.teams</code> table
     */
    fun teams(): TeamsPath {
        if (!this::_teams.isInitialized)
            _teams = TeamsPath(this, null, TEAMS__TEAMS_CREATED_BY_FKEY.inverseKey)

        return _teams;
    }

    val teams: TeamsPath
        get(): TeamsPath = teams()

    private lateinit var _tournamentOrganizers: TournamentOrganizersPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.tournament_organizers</code> table
     */
    fun tournamentOrganizers(): TournamentOrganizersPath {
        if (!this::_tournamentOrganizers.isInitialized)
            _tournamentOrganizers = TournamentOrganizersPath(this, null, TOURNAMENT_ORGANIZERS__TOURNAMENT_ORGANIZERS_USER_ID_FKEY.inverseKey)

        return _tournamentOrganizers;
    }

    val tournamentOrganizers: TournamentOrganizersPath
        get(): TournamentOrganizersPath = tournamentOrganizers()

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.tournaments</code> table, via the
     * <code>registrations_tournament_id_fkey</code> key
     */
    val registrationsTournamentIdFkey: TournamentsPath
        get(): TournamentsPath = registrations().tournaments()

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.tournaments</code> table, via the
     * <code>tournament_organizers_tournament_id_fkey</code> key
     */
    val tournamentOrganizersTournamentIdFkey: TournamentsPath
        get(): TournamentsPath = tournamentOrganizers().tournaments()
    override fun `as`(alias: String): Users = Users(DSL.name(alias), this)
    override fun `as`(alias: Name): Users = Users(alias, this)
    override fun `as`(alias: Table<*>): Users = Users(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Users = Users(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Users = Users(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Users = Users(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Users = Users(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Users = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Users = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Users = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Users = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Users = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Users = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Users = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Users = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Users = where(DSL.notExists(select))
}
