/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables


import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.example.backend.database.Public
import org.example.backend.database.keys.USERSDB_PKEY
import org.example.backend.database.keys.USERSDB_USERNAME_KEY
import org.example.backend.database.tables.records.UsersdbRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Usersdb(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, UsersdbRecord>?,
    parentPath: InverseForeignKey<out Record, UsersdbRecord>?,
    aliased: Table<UsersdbRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<UsersdbRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.usersdb</code>
         */
        val USERSDB: Usersdb = Usersdb()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UsersdbRecord> = UsersdbRecord::class.java

    /**
     * The column <code>public.usersdb.id</code>.
     */
    val ID: TableField<UsersdbRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.usersdb.username</code>.
     */
    val USERNAME: TableField<UsersdbRecord, String?> = createField(DSL.name("username"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>public.usersdb.password_hash</code>.
     */
    val PASSWORD_HASH: TableField<UsersdbRecord, String?> = createField(DSL.name("password_hash"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.usersdb.role</code>.
     */
    val ROLE: TableField<UsersdbRecord, String?> = createField(DSL.name("role"), SQLDataType.VARCHAR(20).defaultValue(DSL.field(DSL.raw("'USER'::character varying"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.usersdb.created_at</code>.
     */
    val CREATED_AT: TableField<UsersdbRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<UsersdbRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<UsersdbRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<UsersdbRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.usersdb</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.usersdb</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.usersdb</code> table reference
     */
    constructor(): this(DSL.name("usersdb"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<UsersdbRecord> = USERSDB_PKEY
    override fun getUniqueKeys(): List<UniqueKey<UsersdbRecord>> = listOf(USERSDB_USERNAME_KEY)
    override fun `as`(alias: String): Usersdb = Usersdb(DSL.name(alias), this)
    override fun `as`(alias: Name): Usersdb = Usersdb(alias, this)
    override fun `as`(alias: Table<*>): Usersdb = Usersdb(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Usersdb = Usersdb(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Usersdb = Usersdb(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Usersdb = Usersdb(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Usersdb = Usersdb(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Usersdb = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Usersdb = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Usersdb = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Usersdb = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Usersdb = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Usersdb = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Usersdb = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Usersdb = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Usersdb = where(DSL.notExists(select))
}
