/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables.records


import java.time.OffsetDateTime
import java.util.UUID

import org.example.backend.database.tables.Announcements
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AnnouncementsRecord private constructor() : UpdatableRecordImpl<AnnouncementsRecord>(Announcements.ANNOUNCEMENTS) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var tournamentId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var kind: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open var message: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(4, value)
        get(): OffsetDateTime? = get(4) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised AnnouncementsRecord
     */
    constructor(id: UUID? = null, tournamentId: UUID, kind: String, message: String, createdAt: OffsetDateTime? = null): this() {
        this.id = id
        this.tournamentId = tournamentId
        this.kind = kind
        this.message = message
        this.createdAt = createdAt
        resetChangedOnNotNull()
    }
}
