/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables.records


import java.time.OffsetDateTime
import java.util.UUID

import org.example.backend.database.enums.DisputeStatus
import org.example.backend.database.tables.Disputes
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DisputesRecord private constructor() : UpdatableRecordImpl<DisputesRecord>(Disputes.DISPUTES) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var matchId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var openedBy: UUID
        set(value): Unit = set(2, value)
        get(): UUID = get(2) as UUID

    open var evidenceUrl: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var status: DisputeStatus?
        set(value): Unit = set(4, value)
        get(): DisputeStatus? = get(4) as DisputeStatus?

    open var resolvedBy: UUID?
        set(value): Unit = set(5, value)
        get(): UUID? = get(5) as UUID?

    open var resolution: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(7, value)
        get(): OffsetDateTime? = get(7) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised DisputesRecord
     */
    constructor(id: UUID? = null, matchId: UUID, openedBy: UUID, evidenceUrl: String? = null, status: DisputeStatus? = null, resolvedBy: UUID? = null, resolution: String? = null, createdAt: OffsetDateTime? = null): this() {
        this.id = id
        this.matchId = matchId
        this.openedBy = openedBy
        this.evidenceUrl = evidenceUrl
        this.status = status
        this.resolvedBy = resolvedBy
        this.resolution = resolution
        this.createdAt = createdAt
        resetChangedOnNotNull()
    }
}
