/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables.records


import java.util.UUID

import org.example.backend.database.tables.GameAccounts
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class GameAccountsRecord private constructor() : UpdatableRecordImpl<GameAccountsRecord>(GameAccounts.GAME_ACCOUNTS) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var userId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var game: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open var identifier: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised GameAccountsRecord
     */
    constructor(id: UUID? = null, userId: UUID, game: String, identifier: String): this() {
        this.id = id
        this.userId = userId
        this.game = game
        this.identifier = identifier
        resetChangedOnNotNull()
    }
}
