/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables.records


import java.time.OffsetDateTime
import java.util.UUID

import org.example.backend.database.enums.JobStatus
import org.example.backend.database.enums.JobType
import org.example.backend.database.tables.Jobs
import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JobsRecord private constructor() : UpdatableRecordImpl<JobsRecord>(Jobs.JOBS) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var type: JobType
        set(value): Unit = set(1, value)
        get(): JobType = get(1) as JobType

    open var status: JobStatus?
        set(value): Unit = set(2, value)
        get(): JobStatus? = get(2) as JobStatus?

    open var payload: JSONB
        set(value): Unit = set(3, value)
        get(): JSONB = get(3) as JSONB

    open var fileUrl: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var error: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var createdBy: UUID?
        set(value): Unit = set(6, value)
        get(): UUID? = get(6) as UUID?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(7, value)
        get(): OffsetDateTime? = get(7) as OffsetDateTime?

    open var finishedAt: OffsetDateTime?
        set(value): Unit = set(8, value)
        get(): OffsetDateTime? = get(8) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised JobsRecord
     */
    constructor(id: UUID? = null, type: JobType, status: JobStatus? = null, payload: JSONB, fileUrl: String? = null, error: String? = null, createdBy: UUID? = null, createdAt: OffsetDateTime? = null, finishedAt: OffsetDateTime? = null): this() {
        this.id = id
        this.type = type
        this.status = status
        this.payload = payload
        this.fileUrl = fileUrl
        this.error = error
        this.createdBy = createdBy
        this.createdAt = createdAt
        this.finishedAt = finishedAt
        resetChangedOnNotNull()
    }
}
