/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables.records


import java.time.LocalDateTime

import org.example.backend.database.tables.Matchdb
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class MatchdbRecord private constructor() : UpdatableRecordImpl<MatchdbRecord>(Matchdb.MATCHDB) {

    open var id: Long
        set(value): Unit = set(0, value)
        get(): Long = get(0) as Long

    open var tournamentId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    open var player1Id: Long
        set(value): Unit = set(2, value)
        get(): Long = get(2) as Long

    open var player2Id: Long
        set(value): Unit = set(3, value)
        get(): Long = get(3) as Long

    open var winnerId: Long?
        set(value): Unit = set(4, value)
        get(): Long? = get(4) as Long?

    open var scorePlayer1: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var scorePlayer2: Int?
        set(value): Unit = set(6, value)
        get(): Int? = get(6) as Int?

    open var playedAt: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(8, value)
        get(): LocalDateTime? = get(8) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised MatchdbRecord
     */
    constructor(id: Long, tournamentId: Long, player1Id: Long, player2Id: Long, winnerId: Long? = null, scorePlayer1: Int? = null, scorePlayer2: Int? = null, playedAt: LocalDateTime? = null, createdAt: LocalDateTime? = null): this() {
        this.id = id
        this.tournamentId = tournamentId
        this.player1Id = player1Id
        this.player2Id = player2Id
        this.winnerId = winnerId
        this.scorePlayer1 = scorePlayer1
        this.scorePlayer2 = scorePlayer2
        this.playedAt = playedAt
        this.createdAt = createdAt
        resetChangedOnNotNull()
    }
}
