/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables.records


import java.util.UUID

import org.example.backend.database.tables.MatchGames
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class MatchGamesRecord private constructor() : UpdatableRecordImpl<MatchGamesRecord>(MatchGames.MATCH_GAMES) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var matchId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var gameNumber: Int
        set(value): Unit = set(2, value)
        get(): Int = get(2) as Int

    open var score1: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    open var score2: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised MatchGamesRecord
     */
    constructor(id: UUID? = null, matchId: UUID, gameNumber: Int, score1: Int? = null, score2: Int? = null): this() {
        this.id = id
        this.matchId = matchId
        this.gameNumber = gameNumber
        this.score1 = score1
        this.score2 = score2
        resetChangedOnNotNull()
    }
}
