/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables.records


import java.util.UUID

import org.example.backend.database.enums.NotificationChannel
import org.example.backend.database.enums.NotificationEvent
import org.example.backend.database.tables.NotificationSettings
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class NotificationSettingsRecord private constructor() : UpdatableRecordImpl<NotificationSettingsRecord>(NotificationSettings.NOTIFICATION_SETTINGS) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var userId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var channel: NotificationChannel
        set(value): Unit = set(2, value)
        get(): NotificationChannel = get(2) as NotificationChannel

    open var target: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    open var eventType: NotificationEvent
        set(value): Unit = set(4, value)
        get(): NotificationEvent = get(4) as NotificationEvent

    open var enabled: Boolean?
        set(value): Unit = set(5, value)
        get(): Boolean? = get(5) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised NotificationSettingsRecord
     */
    constructor(id: UUID? = null, userId: UUID, channel: NotificationChannel, target: String, eventType: NotificationEvent, enabled: Boolean? = null): this() {
        this.id = id
        this.userId = userId
        this.channel = channel
        this.target = target
        this.eventType = eventType
        this.enabled = enabled
        resetChangedOnNotNull()
    }
}
