/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables.records


import java.util.UUID

import org.example.backend.database.enums.PhaseType
import org.example.backend.database.tables.Phases
import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PhasesRecord private constructor() : UpdatableRecordImpl<PhasesRecord>(Phases.PHASES) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var tournamentId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var game: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open var position: Int
        set(value): Unit = set(3, value)
        get(): Int = get(3) as Int

    open var type: PhaseType
        set(value): Unit = set(4, value)
        get(): PhaseType = get(4) as PhaseType

    open var defaultBo: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var settings: JSONB?
        set(value): Unit = set(6, value)
        get(): JSONB? = get(6) as JSONB?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised PhasesRecord
     */
    constructor(id: UUID? = null, tournamentId: UUID, game: String, position: Int, type: PhaseType, defaultBo: Int? = null, settings: JSONB? = null): this() {
        this.id = id
        this.tournamentId = tournamentId
        this.game = game
        this.position = position
        this.type = type
        this.defaultBo = defaultBo
        this.settings = settings
        resetChangedOnNotNull()
    }
}
