/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables.records


import java.time.OffsetDateTime
import java.util.UUID

import org.example.backend.database.enums.RegistrationStatus
import org.example.backend.database.tables.Registrations
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class RegistrationsRecord private constructor() : UpdatableRecordImpl<RegistrationsRecord>(Registrations.REGISTRATIONS) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var tournamentId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var teamId: UUID?
        set(value): Unit = set(2, value)
        get(): UUID? = get(2) as UUID?

    open var userId: UUID?
        set(value): Unit = set(3, value)
        get(): UUID? = get(3) as UUID?

    open var status: RegistrationStatus?
        set(value): Unit = set(4, value)
        get(): RegistrationStatus? = get(4) as RegistrationStatus?

    open var seed: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(6, value)
        get(): OffsetDateTime? = get(6) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised RegistrationsRecord
     */
    constructor(id: UUID? = null, tournamentId: UUID, teamId: UUID? = null, userId: UUID? = null, status: RegistrationStatus? = null, seed: Int? = null, createdAt: OffsetDateTime? = null): this() {
        this.id = id
        this.tournamentId = tournamentId
        this.teamId = teamId
        this.userId = userId
        this.status = status
        this.seed = seed
        this.createdAt = createdAt
        resetChangedOnNotNull()
    }
}
