/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables.records


import java.time.OffsetDateTime
import java.util.UUID

import org.example.backend.database.tables.ScoreReports
import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ScoreReportsRecord private constructor() : UpdatableRecordImpl<ScoreReportsRecord>(ScoreReports.SCORE_REPORTS) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var matchId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var reportedBy: UUID
        set(value): Unit = set(2, value)
        get(): UUID = get(2) as UUID

    open var scores: JSONB
        set(value): Unit = set(3, value)
        get(): JSONB = get(3) as JSONB

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(4, value)
        get(): OffsetDateTime? = get(4) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised ScoreReportsRecord
     */
    constructor(id: UUID? = null, matchId: UUID, reportedBy: UUID, scores: JSONB, createdAt: OffsetDateTime? = null): this() {
        this.id = id
        this.matchId = matchId
        this.reportedBy = reportedBy
        this.scores = scores
        this.createdAt = createdAt
        resetChangedOnNotNull()
    }
}
