/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables.records


import java.time.OffsetDateTime
import java.util.UUID

import org.example.backend.database.enums.TeamMemberRole
import org.example.backend.database.tables.TeamMembers
import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TeamMembersRecord private constructor() : UpdatableRecordImpl<TeamMembersRecord>(TeamMembers.TEAM_MEMBERS) {

    open var teamId: UUID
        set(value): Unit = set(0, value)
        get(): UUID = get(0) as UUID

    open var userId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var role: TeamMemberRole?
        set(value): Unit = set(2, value)
        get(): TeamMemberRole? = get(2) as TeamMemberRole?

    open var joinedAt: OffsetDateTime?
        set(value): Unit = set(3, value)
        get(): OffsetDateTime? = get(3) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<UUID?, UUID?> = super.key() as Record2<UUID?, UUID?>

    /**
     * Create a detached, initialised TeamMembersRecord
     */
    constructor(teamId: UUID, userId: UUID, role: TeamMemberRole? = null, joinedAt: OffsetDateTime? = null): this() {
        this.teamId = teamId
        this.userId = userId
        this.role = role
        this.joinedAt = joinedAt
        resetChangedOnNotNull()
    }
}
