/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables.records


import java.time.OffsetDateTime
import java.util.UUID

import org.example.backend.database.tables.Teams
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TeamsRecord private constructor() : UpdatableRecordImpl<TeamsRecord>(Teams.TEAMS) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var name: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var tag: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var logoUrl: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var createdBy: UUID?
        set(value): Unit = set(4, value)
        get(): UUID? = get(4) as UUID?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(5, value)
        get(): OffsetDateTime? = get(5) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised TeamsRecord
     */
    constructor(id: UUID? = null, name: String, tag: String? = null, logoUrl: String? = null, createdBy: UUID? = null, createdAt: OffsetDateTime? = null): this() {
        this.id = id
        this.name = name
        this.tag = tag
        this.logoUrl = logoUrl
        this.createdBy = createdBy
        this.createdAt = createdAt
        resetChangedOnNotNull()
    }
}
