/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables.records


import java.time.LocalDate

import org.example.backend.database.tables.Tournamentdb
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TournamentdbRecord private constructor() : UpdatableRecordImpl<TournamentdbRecord>(Tournamentdb.TOURNAMENTDB) {

    open var id: Long
        set(value): Unit = set(0, value)
        get(): Long = get(0) as Long

    open var name: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var startDate: LocalDate?
        set(value): Unit = set(2, value)
        get(): LocalDate? = get(2) as LocalDate?

    open var endDate: LocalDate?
        set(value): Unit = set(3, value)
        get(): LocalDate? = get(3) as LocalDate?

    open var maxPlayers: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var status: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised TournamentdbRecord
     */
    constructor(id: Long, name: String, startDate: LocalDate? = null, endDate: LocalDate? = null, maxPlayers: Int? = null, status: String? = null): this() {
        this.id = id
        this.name = name
        this.startDate = startDate
        this.endDate = endDate
        this.maxPlayers = maxPlayers
        this.status = status
        resetChangedOnNotNull()
    }
}
