/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables.records


import java.util.UUID

import org.example.backend.database.enums.OrganizerRole
import org.example.backend.database.tables.TournamentOrganizers
import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TournamentOrganizersRecord private constructor() : UpdatableRecordImpl<TournamentOrganizersRecord>(TournamentOrganizers.TOURNAMENT_ORGANIZERS) {

    open var tournamentId: UUID
        set(value): Unit = set(0, value)
        get(): UUID = get(0) as UUID

    open var userId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var role: OrganizerRole?
        set(value): Unit = set(2, value)
        get(): OrganizerRole? = get(2) as OrganizerRole?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<UUID?, UUID?> = super.key() as Record2<UUID?, UUID?>

    /**
     * Create a detached, initialised TournamentOrganizersRecord
     */
    constructor(tournamentId: UUID, userId: UUID, role: OrganizerRole? = null): this() {
        this.tournamentId = tournamentId
        this.userId = userId
        this.role = role
        resetChangedOnNotNull()
    }
}
