/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables.records


import java.time.OffsetDateTime
import java.util.UUID

import org.example.backend.database.enums.TournamentStatus
import org.example.backend.database.enums.TournamentVisibility
import org.example.backend.database.tables.Tournaments
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TournamentsRecord private constructor() : UpdatableRecordImpl<TournamentsRecord>(Tournaments.TOURNAMENTS) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var name: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var description: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var visibility: TournamentVisibility?
        set(value): Unit = set(3, value)
        get(): TournamentVisibility? = get(3) as TournamentVisibility?

    open var status: TournamentStatus?
        set(value): Unit = set(4, value)
        get(): TournamentStatus? = get(4) as TournamentStatus?

    open var teamSize: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var maxParticipants: Int?
        set(value): Unit = set(6, value)
        get(): Int? = get(6) as Int?

    open var checkInRequired: Boolean?
        set(value): Unit = set(7, value)
        get(): Boolean? = get(7) as Boolean?

    open var checkInWindowMinutes: Int?
        set(value): Unit = set(8, value)
        get(): Int? = get(8) as Int?

    open var registrationOpenAt: OffsetDateTime?
        set(value): Unit = set(9, value)
        get(): OffsetDateTime? = get(9) as OffsetDateTime?

    open var registrationCloseAt: OffsetDateTime?
        set(value): Unit = set(10, value)
        get(): OffsetDateTime? = get(10) as OffsetDateTime?

    open var startAt: OffsetDateTime?
        set(value): Unit = set(11, value)
        get(): OffsetDateTime? = get(11) as OffsetDateTime?

    open var endAt: OffsetDateTime?
        set(value): Unit = set(12, value)
        get(): OffsetDateTime? = get(12) as OffsetDateTime?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(13, value)
        get(): OffsetDateTime? = get(13) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised TournamentsRecord
     */
    constructor(id: UUID? = null, name: String, description: String? = null, visibility: TournamentVisibility? = null, status: TournamentStatus? = null, teamSize: Int? = null, maxParticipants: Int? = null, checkInRequired: Boolean? = null, checkInWindowMinutes: Int? = null, registrationOpenAt: OffsetDateTime? = null, registrationCloseAt: OffsetDateTime? = null, startAt: OffsetDateTime? = null, endAt: OffsetDateTime? = null, createdAt: OffsetDateTime? = null): this() {
        this.id = id
        this.name = name
        this.description = description
        this.visibility = visibility
        this.status = status
        this.teamSize = teamSize
        this.maxParticipants = maxParticipants
        this.checkInRequired = checkInRequired
        this.checkInWindowMinutes = checkInWindowMinutes
        this.registrationOpenAt = registrationOpenAt
        this.registrationCloseAt = registrationCloseAt
        this.startAt = startAt
        this.endAt = endAt
        this.createdAt = createdAt
        resetChangedOnNotNull()
    }
}
