/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables.records


import java.time.OffsetDateTime
import java.util.UUID

import org.example.backend.database.tables.Users
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UsersRecord private constructor() : UpdatableRecordImpl<UsersRecord>(Users.USERS) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var keycloakId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var pseudo: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open var email: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(4, value)
        get(): OffsetDateTime? = get(4) as OffsetDateTime?

    open var avatarUrl: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised UsersRecord
     */
    constructor(id: UUID? = null, keycloakId: String? = null, pseudo: String, email: String? = null, createdAt: OffsetDateTime? = null, avatarUrl: String? = null): this() {
        this.id = id
        this.keycloakId = keycloakId
        this.pseudo = pseudo
        this.email = email
        this.createdAt = createdAt
        this.avatarUrl = avatarUrl
        resetChangedOnNotNull()
    }
}
