/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables.records


import java.time.LocalDateTime

import org.example.backend.database.tables.Usersdb
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UsersdbRecord private constructor() : UpdatableRecordImpl<UsersdbRecord>(Usersdb.USERSDB) {

    open var id: Long
        set(value): Unit = set(0, value)
        get(): Long = get(0) as Long

    open var username: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var passwordHash: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open var role: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(4, value)
        get(): LocalDateTime? = get(4) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised UsersdbRecord
     */
    constructor(id: Long, username: String, passwordHash: String, role: String? = null, createdAt: LocalDateTime? = null): this() {
        this.id = id
        this.username = username
        this.passwordHash = passwordHash
        this.role = role
        this.createdAt = createdAt
        resetChangedOnNotNull()
    }
}
