/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database.tables.references


import org.example.backend.database.tables.Matchdb
import org.example.backend.database.tables.Playerdb
import org.example.backend.database.tables.Tournamentdb
import org.example.backend.database.tables.Usersdb



/**
 * The table <code>public.matchdb</code>.
 */
val MATCHDB: Matchdb = Matchdb.MATCHDB

/**
 * The table <code>public.playerdb</code>.
 */
val PLAYERDB: Playerdb = Playerdb.PLAYERDB

/**
 * The table <code>public.tournamentdb</code>.
 */
val TOURNAMENTDB: Tournamentdb = Tournamentdb.TOURNAMENTDB

/**
 * The table <code>public.usersdb</code>.
 */
val USERSDB: Usersdb = Usersdb.USERSDB
