/*
 * This file is generated by jOOQ.
 */
package org.example.backend.database


import kotlin.collections.List

import org.example.backend.database.tables.Matchdb
import org.example.backend.database.tables.Playerdb
import org.example.backend.database.tables.Tournamentdb
import org.example.backend.database.tables.Usersdb
import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.matchdb</code>.
     */
    val MATCHDB: Matchdb get() = Matchdb.MATCHDB

    /**
     * The table <code>public.playerdb</code>.
     */
    val PLAYERDB: Playerdb get() = Playerdb.PLAYERDB

    /**
     * The table <code>public.tournamentdb</code>.
     */
    val TOURNAMENTDB: Tournamentdb get() = Tournamentdb.TOURNAMENTDB

    /**
     * The table <code>public.usersdb</code>.
     */
    val USERSDB: Usersdb get() = Usersdb.USERSDB

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Matchdb.MATCHDB,
        Playerdb.PLAYERDB,
        Tournamentdb.TOURNAMENTDB,
        Usersdb.USERSDB
    )
}
